### ISSUE TITLE
IdentityServer reference token to JWT exchange

### ISSUE THREAD

**Issue by tempworks** [TomPallister/Ocelot#101]
I have a need to exchange a public IdSvr reference token for an internal only JWT. I've created and deployed a custom grant type on my IdSvr that does the exchange. Are there plans to expand Ocelot to allow custom grant types during the upstream request authentication phase and inject the new bearer token (JWT) in the downstream request? If not, I can start coming up with something and submit a PR. Otherwise, I can start on it with guidance on what you were thinking.  -Paul

**Comment by juancash** [comment]
@tempworks 
Sorry, you'll have to wait for Tom (the project owner) to come back on vacation, but I believe there isn't any problem if you want start to work in a solution.

**Comment by TomPallister** [comment]
@tempworks sorry for not replying sooner. I don't have plans to add this feature at the moment however I would welcome a pull request. I'm not even sure how you do the thing you want to do! :(

**Comment by TomPallister** [comment]
Hi there, I'm closing this because it's been quite a few days since this was discussed and I am not planning to implement this feature myself anytime soon.

Sorry!!!

Thanks for your contribution though! :D

**Comment by ggoyal-Axum** [comment]
is there still no support for this feature?
