### ISSUE TITLE
loadBalancer Config Error

### ISSUE THREAD

**Issue by haptear** [TomPallister/Ocelot#103]
this is my laodbalancer config,but run throw the exception  [System.Exception:“Unable to start Ocelot..configuration, errors were ”]
what wrong with the config?
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/web/cms/{urlPath}",
      "DownstreamScheme": "http",
      "DownstreamHost": "localhost",
      "DownstreamPort": 8901,
      "UpstreamPathTemplate": "/cms/{urlPath}",
      "UpstreamHttpMethod": "Get",
      "FileCacheOptions": {
        "TtlSeconds": 15
      },
      "LoadBalancer": "RoundRobin"
    },
    {
      "DownstreamPathTemplate": "/api/web/cms/{urlPath}",
      "DownstreamScheme": "http",
      "DownstreamHost": "localhost",
      "DownstreamPort": 8909,
      "UpstreamPathTemplate": "/cms/{urlPath}",
      "UpstreamHttpMethod": "Get",
      "FileCacheOptions": {
        "TtlSeconds": 15
      },
      "LoadBalancer": "RoundRobin"
    }
  ],
  "GlobalConfiguration": {
    "RequestIdKey": "OcRequestId",
    "ServiceDiscoveryProvider": {
      "Provider": "Consul",
      "Host": "localhost",
      "Port": 8901
    }
  }
}

**Comment by juancash** [comment]
@haptear What version of Ocelot are you using?

**Comment by geffzhang** [comment]
This is a bug, I have fixed , see https://github.com/TomPallister/Ocelot/pull/105
