### ISSUE TITLE
Identity Server integration

### ISSUE THREAD

**Issue by amituna** [TomPallister/Ocelot#108]
I have configured a separate instance hosted at http://localhost:5000 for identity server. 

Question#1: Can I make the Gateway Api a client for IS4(identity server 4). If yes, please help me with the settings given I have following client created in the identity server:

ClientId = "mvc",
AllowedGrantTypes = GrantTypes.Implicit,
RequireConsent = false,
EnableLocalLogin = false,
RedirectUris = { "http://localhost:5002/signin-oidc" },
PostLogoutRedirectUris = { "http://localhost:5002/signout-callback-oidc" },
AllowedScopes =
{
	IdentityServerConstants.StandardScopes.OpenId,
	IdentityServerConstants.StandardScopes.Profile
}

Question#2: If I can make Gateway Api a client for IS4, do I need to make any changes with the routes to take that into consideration.

**Comment by TomPallister** [comment]
@amituna please read [auth docs](https://github.com/TomPallister/Ocelot/wiki/Authentication) to see what how Ocelot currently integrates with identity server. It is very basic integration at the moment and it is not really a client of IdentityServer! 

Hope that helps...happy to discuss any improvements we could make!

**Comment by amituna** [comment]
Please let me start from the very beginning, let me explain what I have done and please review it and tell me what I am missing. I am using implicit flow and Windows Authentication in Identity Server 4.

Startup looks like following:

public async void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            app.UseCookieAuthentication(new CookieAuthenticationOptions{
                AuthenticationScheme = "idsrv.external"
            });
            app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions{
                AuthenticationScheme = "oidc",
		SignInScheme = "idsrv.external",
		Authority = "http://localhost:5000",
		RequireHttpsMetadata = false,
		ClientId = "mvc",
		SaveTokens = true,
	    });
            await app.UseOcelot();
            app.UseMvc();
        }

My configuration route looks like following:
{
      "DownstreamPathTemplate": "/api/HomeGateway/ActionItemsApi/GetActionItems",
      "DownstreamScheme": "http",
      "DownstreamPort": 64000,
      "DownstreamHost": "localhost",
      "UpstreamPathTemplate": "/home/actionitems/view",
      "UpstreamHttpMethod": "Get",
      "AuthenticationOptions": {
        "Provider": "IdentityServer",
        "ProviderRootUrl": "http://localhost:5000",
        "AllowedScopes": [
          "openid",
          "profile"
        ],
      },
      "RequestIdKey": "OcRequestId"
}

When I try to request "http://localhost:8800/home/actionitems/view", I get 401. following is the error log:

info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:8800/home/actionitems/view
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      ocelot pipeline started : OcelotRequestId - not set
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      calling next middleware : OcelotRequestId - not set
dbug: Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware[0]
      started calling request builder middleware : OcelotRequestId - not set
dbug: Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware[0]
      calling next middleware : OcelotRequestId - not set
dbug: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      upstream url path is /home/actionitems/view/ : OcelotRequestId - not set
dbug: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      downstream template is Ocelot.Values.PathTemplate : OcelotRequestId - not set
dbug: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      EndpointRateLimiting is not enabled for Ocelot.Values.PathTemplate : Ocelo
tRequestId - not set
dbug: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      /home/actionitems/view is an authenticated route. AuthenticationMiddleware
 checking if client is authenticated : OcelotRequestId - not set
info: IdentityServer4.AccessTokenValidation.Infrastructure.NopAuthenticationMidd
leware[7]
      Bearer was not authenticated. Failure message: No token found.
dbug: IdentityModel.AspNetCore.ScopeValidation.ScopeValidationMiddleware[0]
      Skipping scope validation because user is anonymous
fail: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      Client has NOT been authenticated for /home/actionitems/view and pipeline
error set. Error Code: UnauthenticatedError Message: Request for authenticated r
oute /home/actionitems/view by  was unauthenticated : OcelotRequestId - not set
dbug: Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware[0]
      succesfully called next middleware : OcelotRequestId - not set
fail: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      1 pipeline errors found in ResponderMiddleware. Setting error response sta
tus code : OcelotRequestId - not set
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      succesfully called middleware : OcelotRequestId - not set
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      ocelot pipeline finished : OcelotRequestId - not set
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 679.0673ms 401

**Comment by amituna** [comment]
I am not sure if it helps, but I do not see any traffic where web api gateway, tries to communicate with IS4.

**Comment by TomPallister** [comment]
Hi @amituna,

 I havent had a chance to look at this yet but will get round to it soon!

**Comment by TomPallister** [comment]
@amituna did you ever get this working?

**Comment by TomPallister** [comment]
http://ocelot.readthedocs.io/en/latest/features/authentication.html#identity-server-bearer-tokens
