### ISSUE TITLE
 Questions about using RateLimitOptions

### ISSUE THREAD

**Issue by pjjwpc** [TomPallister/Ocelot#113]
My first configuration file：
"RateLimitOptions": {
        "RateLimitRule": {
          "Period": "1s",
          "PeriodTimespan": 100,
          "Limit": 5
        },
        "ClientIdHeader": "mvc",
        "HttpStatusCode": 429,
        "QuotaExceededMessage": "你想玩死我么？",
        "RateLimitCounterPrefix": "OrderAPI",
        "EnableRateLimiting": true,
        "DisableRateLimitHeaders": false
      }
I ran the program times wrong：
Unhandled Exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
Investigation found that there is a problem here：
private static bool IsValidPeriod(FileReRoute reRoute)
        {
            string period = reRoute.RateLimitOptions.Period;

            return period.Contains("s") || period.Contains("m") || period.Contains("h") || period.Contains("d");
        }
Period is null；
So I modified my configuration file：
"RateLimitOptions": {
        "RateLimitRule": {
          "Period": "1s",
          "PeriodTimespan": 100,
          "Limit": 5
        },
        "Period": "1s",
        "PeriodTimespan": 100,
        "Limit": 5,
        "ClientIdHeader": "mvc",
        "HttpStatusCode": 429,
        "QuotaExceededMessage": "你想玩死我么？",
        "RateLimitCounterPrefix": "OrderAPI",
        "EnableRateLimiting": true,
        "DisableRateLimitHeaders": false
      }
But it happened during my test
fail: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      Exception caught in global error handler, exception message: Object reference not set to an instance of an object., exception stack:    at Ocelot.Responder.HttpContextResponder<SetResponseOnHttpContext>d__2.MoveNext() in C:\Work\Demo\Ocelot\Responder\HttpContextResponder.cs:line 30
HttpResponseMessage is null !

I don't know what happened here!
英文不好见谅！

**Comment by TomPallister** [comment]
Ohh no! Sorry you are having problems I will try and debug this ASAP!

**Comment by pjjwpc** [comment]
I think an API  corresponds to multiple Client,  each Client should have the related Rate limit

**Comment by geffzhang** [comment]
Please send out your complete configuration, for example：
  {
  "ReRoutes": [
  {
      "DownstreamPathTemplate": "/api/tof/staffleader/{engname}",
      "DownstreamScheme": "http",
      "ServiceName": "FITRightWayAPI",
      "LoadBalancer": "LeastConnection",
      "UpstreamPathTemplate": "/api/tof/staffleader/{engname}",
      "UpstreamHttpMethod": "get",
      "AuthenticationOptions": {
        "Provider": "IdentityServer",
        "ProviderRootUrl": "http://10.52.32.166:20000",
        "RequireHttps": false,
        "ApiName": "lmcore",
        "AllowedScopes": [
          "openid",
          "Profile",
          "offline_access"
        ],
        "ApiSecret": "fitlmrightway"
      },
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 3,
        "DurationOfBreak": 5000,
        "TimeoutValue": 5
      },
      "RateLimitOptions": {
        "ClientWhitelist": [ "clientId1" ],
        "EnableRateLimiting": true,
        "Period": "1m",
        "PeriodTimespan": 15,
        "Limit": 50
      }
    }
  ],
  "GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Provider": "Consul",
      "Host": "10.52.32.166",
      "Port": 20006
    },
    "RateLimitOptions": {
      "ClientIdHeader": "client_id",
      "QuotaExceededMessage": "out of rate limit",
      "DisableRateLimitHeaders": false
    }
  }
}

**Comment by TomPallister** [comment]
Closing this because there hasnt been activity for a while! Feel free to re-open if relavent.
