### ISSUE TITLE
update .net core 2.0 

### ISSUE THREAD

**Issue by geffzhang** [TomPallister/Ocelot#114]
@TomPallister @binarymash  we upgrade to the .net core 2.0  and VS 2017 15.4  project to develop it?

**Comment by TomPallister** [comment]
Hi @geffzhang sounds like a good idea, might do this on a branch to see if AppVeyor can build it! I'm away for a few days but will look at it when I get back!

**Comment by TomPallister** [comment]
OK I'm back! I will try and do this tomorrow 😄

**Comment by binarymash** [comment]
Not sure if the build image has been updated yet in AppVeyor. For now you might need to change the build worked image in appveyor to "vs2017 preview" to pull in the 2.0 sdk - see https://andrewlock.net/building-asp-net-core-2-0-preview-2-packages-on-appveyor/. 

There's possibly some optimisation that can be done on the cake scripts now that restore is an implicit command.

I'll try to find some time to upgrade some of my own projects in the next few days... had a quick half-hearted go last night but got some dependency issues and didn't investigate. If I find anything useful I'll report back.

**Comment by TomPallister** [comment]
Still haven't got round to this hopefully at the weekend!

**Comment by TomPallister** [comment]
@geffzhang this seems to be harder than I first thought it would be.

The main problem is that there seems to be conflicts with the new .net core authentication apis and how the current IdentityServerpackage works. I may need to wait until IdentityServer supports .net core 2.0 before I can upgrade.

I also have a problem where the tests no longer run, they just timeout and complain they cannot find a certain dll.

I will keep working on it!

**Comment by TomPallister** [comment]
Ive tried doing this again...was blocked because I dont think IdentitySever middleware is upgraded yet.

Also have to do this https://github.com/aspnet/Home/issues/2214 to fix authentication for re routes which is a lot of work.

Getting closer but still waiting on id server.

**Comment by stuartsaltzman** [comment]
@TomPallister - re: IdentityServer and .NET Core 2.0 support - IdentityServer4 has a RC for .NET Standard 2.0 (links below). I have also been trying to migrate Ocelot to .NET Core 2.0 on my fork and have been running into an issue to dynamically build the auth pipeline per a request now that Configure/ConfigureServices is done differently in 2.0.

Link: https://github.com/IdentityServer/IdentityServer4/tree/2.0.0-rc1-update1
Nuget: https://www.nuget.org/packages/IdentityServer4/2.0.0-rc1-update1

**Comment by TomPallister** [comment]
@stuartsaltzman check this for the answer to auth pipeline https://github.com/aspnet/Home/issues/2214

I havent been able to get the IdentityServer RC packages to work using Bearer tokens on a sample project. Have you? Thanks for the help!

**Comment by geffzhang** [comment]
https://www.nuget.org/packages/IdentityServer4/2.0.0 has release

**Comment by TomPallister** [comment]
Thanks @geffzhang

**Comment by geffzhang** [comment]
@TomPallister How is the progress of upgrading. NET Core 2.0, and recently, Microsoft and I have been filming my project using Ocelot's promotional video, which will be advertised at technical meetings in Beijing and New York, with a focus on the Ocelot project

**Comment by TomPallister** [comment]
@geffzhang that sounds amazing! The last time I checked the identity server middleware did not support bearer token workflow in .net core 2.0. I'll have another look and see if it's supported now.

**Comment by TomPallister** [comment]
It looks like it works now so I'll start working on the upgrade again! I need to rewrite all the authentication code due to major breaking changes in .net core 2.0!

**Comment by TomPallister** [comment]
@geffzhang i started working on this again properly and the dependencies seem OK so it shouldn't take too much longer.

**Comment by geffzhang** [comment]
@TomPallister Looking forward to your good news

**Comment by TomPallister** [comment]
I have all the integration tests working again...just the acceptance tests to go! This is all the stuff around how Ocelot handles identityserver tokens...hopefully be done soon!

**Comment by hampos** [comment]
@TomPallister We just started working with Ocelot and want to go .Net Core 2.0 all the way, do you have a timeline for this? If you have a list of things to be done, maybe we could help with a pull request?

**Comment by TomPallister** [comment]
@hampos haha :) yep I'm hoping to have all the tests passing by the start of next week. The main problem is a complete re-write of the authentication stack...which I'm not 100% is going to work but we will see. Once I have all the tests passing I'll put out version 2.0.

**Comment by daniellaoding** [comment]
GOOG IDear       expecting  this milestone

**Comment by TomPallister** [comment]
I've finally got something working! However you can no longer dynamically add or remove authentication providers while Ocelot is running.

I am thinking that I might take the authentication provider information out of the configuration.json and the users would just add there auth providers as following

```csharp
services.AddAuthentication()
                        .AddIdentityServerAuthentication(AKeyForTheScheme, options);
```

This enables the user to add whatever schemes they want. Then in the ReRoute configuration we could say this ReRoute uses this Auth scheme. 

That might work quite nicely..

Or I can just leave the configuration of auth providers in the configuration.json and do the join on auth provider to re route in there.

If anyone has any opinions let me know...

**Comment by TomPallister** [comment]
Im going to move registering the authentication services out of Ocelot so the user can do this themselves and map the scheme to a reroute in config..

**Comment by TomPallister** [comment]
OK I've pushed out the .net core 2.0 update...

You can install with Install-Package Ocelot -Version 2.0.0 when it gets indexed by nuget...

I would suggest looking at https://github.com/TomPallister/Ocelot/wiki/Authentication for the big changes to authentication which effects the structure of configuration.json...

I also suggest looking at https://github.com/TomPallister/Ocelot/blob/develop/test/Ocelot.ManualTest/configuration.json to see how AuthenticationOptions now work.

Hopefully everything is OK...all tests are passing..let me know if there are any problems...

Also sorry my commit messages are not professional, that I didn't do a release candidate and that we will have to fix forward...this is just a hobby so I don't have that much time for it.
