### ISSUE TITLE
Configuration generator

### ISSUE THREAD

**Issue by albertosam** [TomPallister/Ocelot#116]
Hey guys!

I have been make some experiences with Ocelot and a feature that I guess interesting is a configuration json generator. So, I did think in to create a class library project that when imported by a webapi project existent, load a inner controller for read all api controllers and actions and build a json with the reroutes.

Do you think this is useful?

**Comment by TomPallister** [comment]
@albertosam thank you for your interest in the project.

I think this might be useful! It would save people time creating the configurations. I'm not sure how it would work though but you seem to have a good idea.

**Comment by piyey** [comment]
I'm facing this problem right now, did you do something?
I think you could use "Swashbuckle" as an example on how to read all controllers and actions.

https://github.com/domaindrivendev/Swashbuckle.AspNetCore

**Comment by albertosam** [comment]
Exactly! I have a version working. I'll submit on Github.

**Comment by piyey** [comment]
Excelente!!!! Let me know when you submit it please.

**Comment by dbarkwell** [comment]
It's still a WIP but I created an editor that you can use within Ocelot to edit the configuration. It will only (it should at least) allow connections from localhost. I hope to get it finished this week.

https://github.com/dbarkwell/Ocelot.ConfigEditor

**Comment by TomPallister** [comment]
@dbarkwell looks good thanks for helping! I havent had a chance to look at this yet!

**Comment by albertosam** [comment]
Take a look @piyey @TomPallister

https://github.com/albertosam/Ocelot/tree/develop/src/Ocelot.Client

**Comment by piyey** [comment]
Thank you @albertosam , I will take a look at it and test it.
Best regards!

**Comment by piyey** [comment]
@albertosam I'm trying to use Ocelot.Client but I got an error when running the web api:

'Could not load file or assembly 'Ocelot.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. El sistema no puede encontrar el archivo especificado

Do I have to register some service before calling services.AddOcelotConfigurationGen();?

**Comment by albertosam** [comment]
@piyey Try to run the test project https://github.com/albertosam/Ocelot/tree/develop/test/Ocelot.Client.ManualTest

**Comment by piyey** [comment]
@albertosam I did and it worked fine, but when I use it in my project it doesn't work :(

**Comment by albertosam** [comment]
@piyey show the .csproj from your web project

**Comment by piyey** [comment]
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <AssemblyName>ServiciosDistribuidos.Microservicios.Conta.PagosApi</AssemblyName>
    <RootNamespace>ServiciosDistribuidos.Microservicios.Conta.PagosApi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IdentityServer4.AccessTokenValidation" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Infraestructura.Transversales.IoC\Infraestructura.Transversales.IoC.csproj" />
    <ProjectReference Include="..\Ocelot.Client\Ocelot.Client.csproj" />
    <ProjectReference Include="..\ServiciosDistribuidos.Semilla\ServiciosDistribuidos.Semilla.csproj" />
  </ItemGroup>

</Project>
```

**Comment by ravinsp** [comment]
Hi guys, I'm pretty new to Ocelot (and microservices architecture) and still finding my way around this great project. This is a sanity check for my own knowledge. I find this ability to "generate" reroute configs like in Swashbuckle from your microservice's api very useful. But doesn't it go against the very idea of decoupling the API gateway with your microservices? Everytime you change some parameter/action/controller in your microservice api you will have to regenerate the reroute config and redeploy the API gateway.

Ideally, if you specify your reroute config in a very generic way without specifying a mapping for each and every action in the microservice, Ocelot should take care of blindly forwarding the requests. For example, my reroute config looks like the following.

Just one reroute config per microservice is enough. The UI client should append the microservice name to every request url. The `{remainingpart}` placeholder matches with any url/query params.

    "ReRoutes": [
        {
          "UpstreamPathTemplate": "/accounts/{remainingpart}",
          "UpstreamHttpMethod": [],

          "DownstreamPathTemplate": "/api/{remainingpart}",
          "DownstreamScheme": "http",
          "DownstreamHost": "localhost",
          "DownstreamPort": 5000
        },
        {
          "UpstreamPathTemplate": "/products/{remainingpart}",
          "UpstreamHttpMethod": [],

          "DownstreamPathTemplate": "/api/{remainingpart}",
          "DownstreamScheme": "http",
          "DownstreamHost": "localhost",
          "DownstreamPort": 5001
        }
      ]

Are there any reasons to not to go down this path? Should I define reroute configs for every action in the microservice?

**Comment by TomPallister** [comment]
@ravinsp I think your approach is fine. In some scenarios you might want different with load balancer, auth, service discovery rules which is where you will use specific reroutes.

It is also fine to generate your config! One size does not fit all :)
