### ISSUE TITLE
trailing slash

### ISSUE THREAD

**Issue by danny-waite** [TomPallister/Ocelot#117]
Just returned to looking at Ocelot after a few months, good to see things have been progressing nicely.

Main thing I wanted to look at was the ability to work with prefixes as outlined here #86 

I'm seeing a trailing slash being sent to the downstream service which results in a 404 and can't see why.

Here is my config:
```
    {
      "DownstreamPathTemplate": "/alert/{id}",
      "DownstreamScheme": "http",
      "DownstreamHost": "localhost",
      "DownstreamPort": 8010,
      "UpstreamPathTemplate": "/api/alert/{id}"
    }
```

Original Request: `/api/alert/f346bdd5-9d4c-4aea-88d9-3f35c557554d`
Proxied Request: `/alert/f346bdd5-9d4c-4aea-88d9-3f35c557554d/`

I've tried both the stable and unstable releases with the same result.  What am I doing wrong?

**Comment by TomPallister** [comment]
@danny-waite I think this might be something in .net we are using that adds the trailing slash. I'll take a look. Thanks for the interest in the project!!

**Comment by danny-waite** [comment]
no worries Tom, let me know when you've had chance to look, I don't mind digging deeper but thought it best to relay to you first since it seems like a fairly key issue. Would also be interested to know if Ocelot is being used in production and to what scale. Keep up the good work.

**Comment by TomPallister** [comment]
Ive had a look and for some reason I'm always setting the last character of the downstream path as / can't remember why so i'll figure that out and make it work properly..

**Comment by TomPallister** [comment]
I doubt anyone is using Ocelot in production. I'm hoping to use it at work one day. I did some performance testing and didn't notice any memory leaks...Ocelot adds a few ms to each http request in the environment I was testing on in Azure.

**Comment by TomPallister** [comment]
@danny-waite I've got a fix for this on a PR, just waiting for checks to finish and I'll merge it and create a build!

**Comment by TomPallister** [comment]
@danny-waite Ive just pushed a fix for this to nuget....Install-Package Ocelot -Version 1.4.10

I'm going to close the issue now as I think it is fixed...if you run into further problems let me know and I can feel like an idiot! :)

Thanks for submitting this issue :D
