### ISSUE TITLE
There are six '{'s and seven '}'s in the Startup example

### ISSUE THREAD

**Issue by alexinea** [TomPallister/Ocelot#118]
hi @TomPallister . As this issue's title, there are six '{'s and seven '}'s in the first [Startup example](https://github.com/TomPallister/Ocelot/wiki/Startup) in Wiki. 

Pls fix it.  😄

**Comment by TomPallister** [comment]
@alexinea ohhhh sorry! I'll get on it! Thanks for the info.

**Comment by TomPallister** [comment]
@alexinea Ive just changed it, thanks for the help!
