### ISSUE TITLE
Is it possible to upgrade .Net Standard 2.0?

### ISSUE THREAD

**Issue by aqa510415008** [TomPallister/Ocelot#120]
@TomPallister @binarymash @geffzhang 友善大神 
Looking forward to Ocelot upgrade to .Net Standard 2.0?

**Comment by TomPallister** [comment]
Hi @aqa510415008 thanks for contributing! This is a duplicate of #114 

I am going to start working on the upgrade asap. Unfortunately it is not going to be simple.
