### ISSUE TITLE
Question: ocelot OpenIddict Auth integration

### ISSUE THREAD

**Issue by msvaillant** [TomPallister/Ocelot#127]
Good day!

I have got some questions about current Ocelot state and plans. Does Ocelot support work with separated auth and resource server?

Does Ocelot supports auth except of IdentityServer?

For example: I have an Example.Auth solution with OpenIddict issuing JWT and other identity stuff, I have an Example.Core - resource server, Ocelot is ApiGateway for this two services. My scenario: I want Ocelot to Validate OAuth\JWT on requesting resource through this pipeline - is it possible?

P.S. When Ocelot is going to support NetCore 2.0? it is changed auth flow, so now it is on exception with authorization middleware..
P.P.S. Thank you for your great job! I like your project and we are using it for out new microservice based solution!

**Comment by TomPallister** [comment]
Hi @msvaillant Ocelot could support your scenario but it might need some changes to add a new authentication provider. We would need to add an OpenIddict provider. Im dont know about OpenIddict so maybe you could submit a pull request.  This is a PR where @sharpn added a new provider...https://github.com/TomPallister/Ocelot/pull/110.

I do intend to upgrade but its quite complicated and I am waiting for IdentityServer! Or me to work out why it doesnt work!

Thanks for your for contribution.

**Comment by TomPallister** [comment]
Hi there, I'm closing this because it's been quite a few days since this was discussed and I am not planning to implement this feature myself anytime soon.

Sorry!!!

Thanks for your contribution though! :D

**Comment by Sacrilege** [comment]
@TomPallister I'm curious if Ocelot supports OpenIddict out of the box now.

**Comment by erielpo** [comment]
Hi there. I would like to see an example of openiddict + ocelot + api-resource.
