### ISSUE TITLE
A configuration editor for Ocelot

### ISSUE THREAD

**Issue by geffzhang** [TomPallister/Ocelot#141]
https://github.com/dbarkwell/Ocelot.ConfigEditor

**Comment by TomPallister** [comment]
Hi @geffzhang this was made as part of this issue https://github.com/TomPallister/Ocelot/issues/116 

I looks good but I havent had a chance to look at it yet!

**Comment by piyey** [comment]
Nice @geffzhang , I will take a look at it.
Thank you!
