### ISSUE TITLE
Cannot have async Configure in Startup

### ISSUE THREAD

**Issue by theofanis** [TomPallister/Ocelot#143]
In the docs, an `async void Configure()` is showcased. This doesn't work and we should avoid it, since async build is not a thing yet.

Since `UseOcelot` is returning a Task, maybe change this to something like what Stephen Cleary says in this [SO](https://stackoverflow.com/a/32271120).

It took us a bit before we find out why middlewares weren't running when debugging Ocelot.

**Comment by TomPallister** [comment]
arghh i thought i fixex this..sigh..I'll get it fixed asap.

**Comment by theofanis** [comment]
It was always there, sigh.. 😅

It's still with async in the Startup documentation, so if you update this for others it would be great.

**Comment by TomPallister** [comment]
I have updated the wiki! Let me know if you have anymore problems!
