### ISSUE TITLE
File request failure

### ISSUE THREAD

**Issue by cqkisyouq** [TomPallister/Ocelot#145]
At in DownstreamRouteFinderMiddleware 
upstreamUrlPath = upstreamUrlPath.SetLastCharacterAs('/');

At the end of the url added '/',Make the url to access error.

**Comment by TomPallister** [comment]
@cqkisyouq can you post your configuration.json file?

**Comment by cqkisyouq** [comment]
"ReRoutes": [
    {
      "DownstreamPathTemplate": "api/{url}",
      "DownstreamScheme": "http",
      "DownstreamHost": "***",
      "DownstreamPort": "8025",
      "UpstreamPathTemplate": "/platform/{url}",
      //"UpstreamHttpMethod": [ "Get" ],
      //"ServiceName": "newapp",
      //"LoadBalancer": "RoundRobin",
      "QosOptions": {
        "ExceptionsAllowedBeforeBreasking": 3,
        "DurationOfBreak": 10,
        "TimeoutValue": 5000
      }
    }

**Comment by cqkisyouq** [comment]
like this.
/swagger/lib/backbone-min.js  200
/swagger/lib/backbone-min.js/ 404

**Comment by TomPallister** [comment]
@cqkisyouq which version of Ocelot are you using? It should not append the / to the url for the downstream service. Unless I have introduced a bug :(

**Comment by cqkisyouq** [comment]
@TomPallister version 2.0 

Generate matching rules here：
Class ->UpstreamTemplatePatternCreator 

Create(FileReRoute reRoute)  upstreamTemplate = upstreamTemplate.SetLastCharacterAs('/');

**Comment by cqkisyouq** [comment]
@TomPallister I want to access the file How to do?

**Comment by TomPallister** [comment]
@cqkisyouq I'm not sure what you mean by access the file. Could you explain more?

I will write a failing test and see if we can understand the problem.

**Comment by cqkisyouq** [comment]
@TomPallister 
I want to visit the static files
like this url     http://localhost/1.txt

After the ocelot processing into such a url    http://localhost/1.txt/

Returns the status of 404

**Comment by TomPallister** [comment]
@cqkisyouq I've started looking at this issue.

I can see various problems in how I'm building the regex that matches urls. Previously I assumed that it was OK to have urls always end with a forward slash because I didn't think anyone would use Ocelot to serve files! 

Anyway I will see what I can do to get your use case working.

**Comment by TomPallister** [comment]
@cqkisyouq please ignore previous comment.

This class UpstreamTemplatePatternCreator generates the regex that matches the upstream request coming into ocelot. It is not the code that decides what url to use when making a downstream request. I believe your problem is with the downstream request.

I'm struggling to replicate your issue. Please can you tell me which version of Ocelot you are using?

**Comment by TomPallister** [comment]
@cqkisyouq 

I have also noticed this part of your config. That should cause Ocelot to not work. I think you might have an older version of Ocelot. 

```json
"DownstreamPathTemplate": "api/{url}",
```

Please use Install-Package Ocelot -Version 2.0.1 to get the latest!

**Comment by TomPallister** [comment]
Ive got a branch here with some changes that I think fix your issue but I havent been able to get a failing test yet.

https://github.com/TomPallister/Ocelot/tree/feautre/fix-%23145

**Comment by TomPallister** [comment]
OK I have a test for the issue! Pushed with my latest commit to that branch

**Comment by cqkisyouq** [comment]
@TomPallister 
That configuration is version 2.0.

static files：
It can be implemented on branches  https://github.com/TomPallister/Ocelot/tree/feautre/fix-%23145
I see have cancel that code.   // upstreamUrlPath = upstreamUrlPath.SetLastCharacterAs('/');

Thank you for your attention！

**Comment by TomPallister** [comment]
@cqkisyouq please try

Install-Package Ocelot -Version 2.0.2	

Hopefully will work now.
