### ISSUE TITLE
ReRoute has null CacheOptions when being fetched from cache

### ISSUE THREAD

**Issue by hampos** [TomPallister/Ocelot#146]
Hey again @TomPallister 

I tried setting `FileCacheOptions` on my reroute, and have been getting `NullReferenceException` on this line:
https://github.com/TomPallister/Ocelot/blob/1d1a68ff95bb1caf5c279c64e18b5d168e82f7cd/src/Ocelot/Cache/Middleware/OutputCacheMiddleware.cs#L44

On the second time I perform a request on a reroute, and configuration has been cached.

It appears `DownstreamRoute.ReRoute.CacheOptions` is null when fetched from cache, did a little digging there and it seems to be coming from `JsonConvert` being unable to match `fileCacheOptions` with `CacheOptions` (from the JSON) in the constructor of `ReRoute`
https://github.com/TomPallister/Ocelot/blob/1d1a68ff95bb1caf5c279c64e18b5d168e82f7cd/src/Ocelot/Configuration/ReRoute.cs#L22
Tried renaming `fileCacheOptions` to `cacheOptions` and the deserialization happened successfully.

I am onto another error now, not sure if I should open another issue for that.
It's a deserialization error again
```
Exception caught in global error handler, exception message: Unable to find a constructor to use for type System.Net.Http.CurlHandler+CurlResponseMessage. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'Version', line 1, position 11., exception stack:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
```
when trying to fetch from the cache the cached Response object for that ReRoute.
This is the cached data:
```
{
  "Version": {
    "Major": 1,
    "Minor": 1,
    "Build": -1,
    "Revision": -1,
    "MajorRevision": -1,
    "MinorRevision": -1
  },
  "Content": {
    "Headers": [
      {
        "Key": "Content-Length",
        "Value": [
          "142"
        ]
      },
      {
        "Key": "Content-Type",
        "Value": [
          "application/json; charset=utf-8"
        ]
      }
    ]
  },
  "StatusCode": 200,
  "ReasonPhrase": "OK",
  "Headers": [
    {
      "Key": "Date",
      "Value": [
        "Wed, 08 Nov 2017 13:20:08 GMT"
      ]
    },
    {
      "Key": "Server",
      "Value": [
        "Kestrel"
      ]
    }
  ],
  "RequestMessage": {
    "Version": {
      "Major": 1,
      "Minor": 1,
      "Build": -1,
      "Revision": -1,
      "MajorRevision": -1,
      "MinorRevision": -1
    },
    "Content": {
      "Headers": [
        {
          "Key": "Content-Type",
          "Value": [
            ""
          ]
        },
        {
          "Key": "Content-Length",
          "Value": [
            "0"
          ]
        }
      ]
    },
    "Method": {
      "Method": "GET"
    },
    "RequestUri": "http://cs-api/status",
    "Headers": [
      {
        "Key": "Cache-Control",
        "Value": [
          "no-cache"
        ]
      },
      {
        "Key": "Connection",
        "Value": [
          "keep-alive"
        ]
      },
      {
        "Key": "Accept",
        "Value": [
          "*/*"
        ]
      },
      {
        "Key": "Accept-Encoding",
        "Value": [
          "gzip",
          "deflate",
          "br"
        ]
      },
      {
        "Key": "Accept-Language",
        "Value": [
          "en-US",
          "en; q=0.8",
          "el; q=0.6"
        ]
      },
      {
        "Key": "Authorization",
        "Value": [
          "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjU0MTA5OGQyZDJjZDY5MDZlNWQ1MmZkZjk0MDY2NzkxIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MTAwNjA3NDYsImV4cCI6MTUxMDA2NDM0NiwiaXNzIjoiaHR0cDovL2Q2ODNlYTcwLm5ncm9rLmlvIiwiYXVkIjpbImh0dHA6Ly9kNjgzZWE3MC5uZ3Jvay5pby9yZXNvdXJjZXMiLCJhcGkuaWRlbnRpdHkiXSwiY2xpZW50X2lkIjoiYXBpLmlkZW50aXR5LmNsaWVudCIsInNjb3BlIjpbImFwaS5pZGVudGl0eSJdfQ.KzTupFZFxDw3ao6fe32VxkaJNYAT3WSp7L2N-tVCn--zR2APpxbd_tu7hAlc4basAe51FPg2LA_GaiBADlZLW8rGvkrLZiP8B2O0ajQVu5S6p3PBGwEQ1i0YleI2JRUC5jpFYkECRi2MooLe7XIlx9KHrYrAGl5JTIewc5HQqU0rzAgdXyS2VGWoSCXEBZwSD9rZMUP2b6nSxgLCCH1NGREGKjyOTQogpvhGydrMSKwXUXMf4F8KJoZPET9y4cEzoJ6fGmm6SvSwGXSTo0-BCZVlEhyx96A43BalF2ePzxiCTtFIc6HbGhQcQybc-lNNw1vsqA6qfS4iz6nWqagnlA"
        ]
      },
      {
        "Key": "User-Agent",
        "Value": [
          "Mozilla/5.0",
          "(Windows NT 10.0; Win64; x64)",
          "AppleWebKit/537.36",
          "(KHTML, like Gecko)",
          "Chrome/61.0.3163.100",
          "Safari/537.36"
        ]
      },
      {
        "Key": "Postman-Token",
        "Value": [
          "2c2b6d0f-0166-f72f-d52f-54ef0b480ffb"
        ]
      },
      {
        "Key": "OcRequestId",
        "Value": [
          "0HL96L9UB0LMO:00000003"
        ]
      }
    ],
    "Properties": {
      
    }
  },
  "IsSuccessStatusCode": true
}
```

This feels like a platform specific issue, I'm running Ocelot in a docker container from the `microsoft/aspnetcore:2.0` image which is a Debian implementation.

**Comment by hampos** [comment]
Just a small update, I'm using the `Json` serializer on `CacheManager`
```
"serializer": {
  "knownType": "Json"
}
```
since Binary is not available for projects targeting cross platform frameworks.
From the documentation on CacheManager
```
Because binary serialization is not available in the .NET core clr, it cannot be used by projects targeting cross platform frameworks. 
In this case, you have to install e.g. the JSON serializer.
```
It appears that Json.NET cannot deserialize to `CurlResponseMessage` , which is the Unix HttpResponseMessage implementation, since it does not have a valid constructor for that.

https://github.com/dotnet/corefx/blob/70b8ced563d8e818b6f49e8a85983314d0ce2b11/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.CurlResponseMessage.cs#L20

Maybe we could cache another custom structure that can then be mapped to HttpResponseMessage, instead of the message itself?

**Comment by TomPallister** [comment]
@hampos probably create another issue for the CurlResponseMessage problem.

With regards to the cache options naming I can't seem to replicate the issue with a failing test. Is this something you could help me with?

**Comment by hampos** [comment]
@TomPallister Sure I'll give it a shot,
It's probably not possible to create a unit test for this because the problem lies in the deserialization of the cached JSON value by CacheManager's `ICacheSerializer` implementation.
This will probably have to be an acceptance test that spins up Ocelot with a CacheManager configuration using an in-memory handler in order to be replicated.
I am not sure if CacheManager's in-memory handler will use the Json Serializer though, I think it stores object references in memory.
Will look into it and report back.

**Comment by TomPallister** [comment]
@hampos I think it just stores the object in memory and doesnt serialise because I already have an acceptance test for this and it works. Debugged it this morning and seemed fine.

**Comment by hampos** [comment]
Hey @TomPallister 
I've opened a pull request for the acceptance test here:
https://github.com/TomPallister/Ocelot/pull/151

**Comment by TomPallister** [comment]
waiting for release

**Comment by TomPallister** [comment]
released a new package
Install-Package Ocelot -Version 2.0.1
should work a bit better now.
