### ISSUE TITLE
file configuration error validate error message always empty in exception message

### ISSUE THREAD

**Issue by Eilyyyy** [TomPallister/Ocelot#156]
error message create in here,
https://github.com/TomPallister/Ocelot/blob/d3774820137c00fea50b6d01fff8f4089f6df305/src/Ocelot/Configuration/Validator/FileConfigurationValidator.cs#L33 
 you send the error result to the OkResponse object but OkResponse's constructor not set the error list to her Errors propertity, and here https://github.com/TomPallister/Ocelot/blob/d3774820137c00fea50b6d01fff8f4089f6df305/src/Ocelot/Configuration/Creator/FileOcelotConfigurationCreator.cs#L93 you popular the error message with OkResponse's error property so the error always empty.

**Comment by TomPallister** [comment]
@Eilyyyy thanks for letting me know! Must just be a mistake. I will take a look asap.

**Comment by TomPallister** [comment]
started working on this here https://github.com/TomPallister/Ocelot/pull/160
