### ISSUE TITLE
How to participate in the project contribute? 

### ISSUE THREAD

**Issue by geffzhang** [TomPallister/Ocelot#16]
I have a code fork, watching an article, code, I did not continue to update the last month, is used in the project. NET core 1.0, many components already RTM, such as IdentityServer4.AccessTokenValidation, next step is what I expect to be with you contributions to this project

**Comment by TomPallister** [comment]
Hi @geffzhang 

Please submit a pull request, I am happy for your help!

Thanks,

Tom
