### ISSUE TITLE
nodejs microservice 

### ISSUE THREAD

**Issue by kuncevic** [TomPallister/Ocelot#162]
Say if one of my micreserivces written in nodejs can ocelot handle such case? 

Say I want to have this sort of architecture:
`Identityserver`
`OcelotGeteway_api0`
`core2.0_api1`
`core2.0_api2`
`nodejs_api3` (want to make sure If there is a way to take care of this one wih Ocelot Gateway)

**Comment by TomPallister** [comment]
@kuncevic It doesn’t matter what your downstream services are built with if they communicate using http(s).
