### ISSUE TITLE
Integrate with identity server 4

### ISSUE THREAD

**Issue by ZhifuFeng** [TomPallister/Ocelot#167]
Dear Tom,
I would like to use identity server 4 for authencation in ocelot. could you write one blog with detail steps for it?
thank you very much.

**Comment by TomPallister** [comment]
@ZhifuFeng I will improve the documentation ASAP!

**Comment by ZhifuFeng** [comment]
That is great. thank you.

**Comment by TomPallister** [comment]
@ZhifuFeng please read http://ocelot.readthedocs.io/en/latest/features/authentication.html# and http://ocelot.readthedocs.io/en/latest/features/authentication.html#identity-server-bearer-tokens

Does that help?

**Comment by ZhifuFeng** [comment]
@TomPallister  it doesn't work. I use postman to access my API via ocelot , but meet "500 Internal Server Error".
My identity server is working well. I can request one token from it.

Another question:
what is ApiName, ApiSecret mean in below code? it is equeal to attribute ClientId, ClientSecrets of  IdentityServer4.Models.Client?

  Action<IdentityServerAuthenticationOptions> options = o =>
            {
                o.Authority = "http://localhost:5000";
                o.ApiName = "socialnetwork";
                o.SupportedTokens = SupportedTokens.Both;
                o.ApiSecret = "secret";
            };

**Comment by ZhifuFeng** [comment]
what is ApiName, ApiSecret mean in below code? it is mapping to attribute ClientId, ClientSecrets of IdentityServer4.Models.Client?

**Comment by TomPallister** [comment]
@ZhifuFeng ApiName is the name of the IdentityServer4.Models.ApiResource. The secret is one of it's secrets which is the type IdentityServer4.Models.Secret. It does not map to ClientId or ClientSecrets.

**Comment by ZhifuFeng** [comment]
@TomPallister 
Below is the code in Identity Server4 Auth Server, it doesn't specify any secret, so i can set o.ApiSecret  as blank, right? should i set any claimType for the apiResource?

    public static IEnumerable<ApiResource> ApiResources()
        {
            return new[]
            {
                new ApiResource("socialnetwork","socialnetwork")
            };
        }

**Comment by TomPallister** [comment]
@ZhifuFeng yes you would not need to set the secret. 

All you are doing is using the [IdentityServer4.AccessToken middleware](https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation). If you read the instructions from IdentityServer how to use this that might help.

**Comment by ZhifuFeng** [comment]
@TomPallister it work well now with identity server 4. thank you very much.
it is important to add option **_RequireHttpsMetadata =false_**, otherwise will meet 500 error.

 services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
            .AddIdentityServerAuthentication(authenticationProviderKey, options =>
            {
                options.RequireHttpsMetadata = false;
                options.Authority = "http://localhost:5000";
                options.ApiName = "socialnetwork";
            });
