### ISSUE TITLE
Ocelot Added  service discovery

### ISSUE THREAD

**Issue by geffzhang** [TomPallister/Ocelot#17]
I need to add a combination of Consul (https://www.consul.io/)to Ocelot service discovery functions, Ocelot via the specific services that are currently available from Consul services and then call the service, I'm trying to implement this functionality, mainly DownstreamTemplate is dynamically modified, how the configuration item and better

**Comment by TomPallister** [comment]
HI @geffzhang I don't understand what you want to do. Please would you be able to create a diagram that shows your plan?

At the moment Ocelot gets all of its configuration from a json file. The DownstreamTemplate cannot be modified after the ReRoute has been created.

I guess we need to allow this to change after the Ocelot service has started running?

**Comment by geffzhang** [comment]
I thought for a few days, using these to build a micro services ASP.NET.core + Consul(https://www.consul.io/)+Fabio（https://github.com/eBay/fabio） + ocelot, raised this issue, I think: ASP.NET core + conul + ocelot,  ocelot supports load balancing , Use eBay fabio more suitable  to do routing

**Comment by TomPallister** [comment]
I have not used Fabio before so I will need some time to understand it.

My idea i for Ocelot is

Load Balancer > Ocelot (cluster) > Load Balancer (fabio????) > Service Discovery (consul) > Downstream Service

Is this what you want to do? 

It would be quite easy to make Ocelot load balance using queues.

**Comment by geffzhang** [comment]
Fabio is optional ，Ocelot try Fabio directly under current state 
more direct way is
Ocelot looks up service address from Consul , 
Ocelot makes request to downstream service load balancing across the available instances of a service

**Comment by TomPallister** [comment]
Ahh..I was going to implement that feature soon. Good.

**Comment by TomPallister** [comment]
@geffzhang I have split the DownstreamTemplate into parts..see pull request [here](https://github.com/TomPallister/Ocelot/pull/18)

If tests pass I will merge. Next will be service discovery integration.

**Comment by geffzhang** [comment]
I pull your code, combined with service discovery,  need to add a router, similar to Fabio's role, obtained by Consul to multiple instances of the service, need to implement load balancing features ,such as  RoundRobinAddress

**Comment by TomPallister** [comment]
@geffzhang I have started working on implementing the service discovery with consul. It will take a few days at least!

**Comment by geffzhang** [comment]
Please @TomPallister Code reviews [Refactor load balancers and implementing Consul Service discovery](https://github.com/TomPallister/Ocelot/pull/22)

**Comment by TomPallister** [comment]
@geffzhang I have created pull request from feature/servicediscovery. I still need to get the Consul acceptance test passing and check manually. I am implementing minimal features for ConsulServiceProvider and we can add more later.

**Comment by geffzhang** [comment]
@TomPallister Very exciting, I think you've completed all of the features of the code, you need to celebrate, I want to write articles to promote this project, my English is not so good, only can write Chinese articles

**Comment by geffzhang** [comment]
Today I wrote an article http://www.cnblogs.com/shanyou/p/6366360.html briefly mentioned the Ocelot, many developers are concerned that the Ocelot

**Comment by TomPallister** [comment]
@geffzhang thank you very much. I will add you as collaborator.

Please feel free to merge #23
