### ISSUE TITLE
AppVeyor doesnt fail build when it fails

### ISSUE THREAD

**Issue by TomPallister** [TomPallister/Ocelot#172]
No idea why but AppVeyor doesnt fail build when it fails.

e.g. https://ci.appveyor.com/project/TomPallister/ocelot-fcfpb/build/2.1.0-PullRequest.168+20.build.425

Work out why and fix.

**Comment by TomPallister** [comment]
Could be this https://github.com/cake-build/cake/issues/1478

**Comment by binarymash** [comment]
@TomPallister out of interest did the exit statement fix the problem? Got a few pipelines of my own to fix... ;)

**Comment by TomPallister** [comment]
@binarymash yes it did!
