### ISSUE TITLE
Optimise build scripts

### ISSUE THREAD

**Issue by binarymash** [TomPallister/Ocelot#177]
There's a couple of things we can do to make the build scripts run a little bit faster:

- with dotnet core sdk 2.0 restore is now implicit during build. So, we can remove the explicit restore step from the build
- when we run tests it will currently rebuild the project. Given that the tests depend on the compile task we don't need this, and we can prevent it by passing in the --no-build argument to the test runner. 

However, a gotcha here is that the unit tests need to be built with debug symbols for the coverage reports to work. So, shouldn't pass --no-build for unit tests, as we need to explicitly build debug versions of the assemblies that the tests are covering.

**Comment by TomPallister** [comment]
@binarymash shall we close this one?

**Comment by binarymash** [comment]
Yep.
