### ISSUE TITLE
Update documentation to asp.net core 2.0

### ISSUE THREAD

**Issue by KhalilMohammad** [TomPallister/Ocelot#180]
Provide documentation for both asp.net core 1.x and asp.net core 2.x for both program.cs and startup.cs

**Comment by TomPallister** [comment]
Hi @KhalilMohammad thanks for your interest in the project!

Can I ask what your motivation is for asp.net core 1.0 documentation? I'm a bit confused because Ocelot is now an netcoreapp2.0 project only!

**Comment by KhalilMohammad** [comment]
Actually I am not interested in asp.net 1.0 but I have seem parts of documents which are asp.net 1.0 only.
For example startup.cs and program.cs

**Comment by TomPallister** [comment]
Ohh do they not work for asp.net core 2.0?

I might have missed that in the docs :(

**Comment by KhalilMohammad** [comment]
I managed to get it working but I would love to have docs that cover all cases.

**Comment by TomPallister** [comment]
What changes did you need to make to get it working? I can use that for the docs!

**Comment by KhalilMohammad** [comment]
Sorry for late reply. I was on holiday. I will be sending changes soon.

**Comment by TomPallister** [comment]
@KhalilMohammad Updated the docs here http://ocelot.readthedocs.io/en/latest/introduction/gettingstarted.html#net-core-2-0 let me know if you think I should add anything else.

Thanks for the interest in the project and contributing!! :D
