### ISSUE TITLE
ocelot + consul load balancing recovery service api problem

### ISSUE THREAD

**Issue by axzxs2001** [TomPallister/Ocelot#181]
I use ocelot + consul service discovery, when the same service api configuration two consul server node, the load balancing can work normally, when a service exits, ocelot can no longer request the correct exit service api, but when this service is back to normal, how can we allow the load balance to access this service API again？

**Comment by TomPallister** [comment]
Hi @axzxs2001, thank you for your interest in the project.

I do not fully understand the issue. Would it be possible to write a failing test showing the problem? Ocelot already has the infrastructure in place to write tests around the consul load balancing.

If not please provide more detail and I will try and work it out!

**Comment by axzxs2001** [comment]
thank you, in configuration.json ,I change "LoadBalancer" to  "RoundRobin" is ok.

**Comment by TomPallister** [comment]
Re-opening because I would like to look into this more

**Comment by axzxs2001** [comment]
Hi, firstly, I set LeastConnection for LoadBalancer option in my configuration file.
However, one of my node in the cluster is down, after restarting the service, ocelot
can't auto find the restarted node. Then I changed the LoadBalancer option as RoundRobin,
Ocelot can find the restartd service well. So it looks like I use a wrong value for
LoadBalancer config option.

**Comment by TomPallister** [comment]
@axzxs2001 this problem was a bug LeastConnection should work.

I have fixed it in PR #195 this will get merged soon.
