### ISSUE TITLE
Logging not writing OcelotRequestId

### ISSUE THREAD

**Issue by xxsybreedxx** [TomPallister/Ocelot#183]
Hi, im using Ocelot v2.0.4 and I'm facing a minor issue with logging (or maybe my configuration is wrong).

In my case I am using basic implementation. 

![default](https://user-images.githubusercontent.com/3993463/34395374-566d7cdc-eb68-11e7-962c-fbfd2684acc8.png)

My configuration file:

  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/values",
      "DownstreamScheme": "http",
      "DownstreamHost": "localhost",
      "DownstreamPort": 57670,
      "UpstreamPathTemplate": "/api/values",
      "UpstreamHttpMethod": [ "Get" ]
    }
  ],
  "GlobalConfiguration": {
    "RequestIdKey": "OcRequestId"
  }

Downstream WebApi is recieving the OcRequestId header

![default](https://user-images.githubusercontent.com/3993463/34395436-dce1af72-eb68-11e7-83cc-29402a8d7ae3.png)

I'm just trying to log incoming requests and responses somehow, not implementing custom things.

**Comment by TomPallister** [comment]
@xxsybreedxx hey thanks for contributing! The config looks OK to me so not sure why it doesn't work.

I will have a look when I get a chance! On my open source holiday at the moment ;)

**Comment by dbarkwell** [comment]
If I'm reading the code correctly, should: _requestScopedDataRepository.Add("RequestId", requestId.RequestIdValue) be set in SetOcelotRequestId in RequestIdMiddleware.cs?

**Comment by TomPallister** [comment]
@dbarkwell I think so that would make sense it’s been a while since I looked at that middleware. I’m working on another issue then I’ll look at this!

**Comment by TomPallister** [comment]
I think you need IncludeScopes set to true in appsettings.json

{
  "Logging": {
    "IncludeScopes": true,
    "LogLevel": {
      "Default": "Trace",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
}

I haven't checked yet just a quick look. Maybe I have missed this from the docs.

Line 44 of request Id middleware we set 

context.TraceIdentifier = upstreamRequestIds.First();

I cant remember if Ive seen it working after net core 2.0 update.

**Comment by TomPallister** [comment]
Sorry ignore me include scopes gives you the asp.net request id

**Comment by TomPallister** [comment]
Ive hacked some stuff together that got logging working on my local from #189 

I guess we broke this somewhere during a refactor or something. I will see if I can make it better.

**Comment by TomPallister** [comment]
I've just pushed a new version 2.0.8 which fixes the request id problem. 

Hopefully better docs around it here http://ocelot.readthedocs.io/en/latest/features/requestid.html

Please let me know if I've missed anything!
