### ISSUE TITLE
Aggregation of multiple responses from downstream services

### ISSUE THREAD

**Issue by xxsybreedxx** [TomPallister/Ocelot#184]
Hi,

It would be great to have multiple response aggregation functionality. Some time ago I was participating in the development of one microservice-based solution, and there was  a custom made API Gateway service which was able to create multiple requests to different downstream services, then, when all responses are received Gateway was making a data aggreagation (from multiple DTOs to single one). It was a nice approach for UI, instead of multiple requests we were able to collect data from multiple microservices at once.

Is it possible to do something similar with Ocelot? 

Example: 

UI [api/something] => Ocelot [api1/resource1, api2/resource2, ...] => Aggregate and return single object

**Comment by TomPallister** [comment]
Hi @xxsybreedxx 

This feature has previously been requested in issue #79 it is something that I have considered implementing but haven't done yet. If this is something you would like to try implement yourself in Ocelot then there has been a discussion around it in that issue.

I will close this as a duplicate of the that issue! Hope thats OK.

**Comment by TomPallister** [comment]
duplicate of #79
