### ISSUE TITLE
  Routing regular expression matching problem

### ISSUE THREAD

**Issue by cqkisyouq** [TomPallister/Ocelot#185]
"DownstreamPathTemplate": "/{url}"
"UpstreamPathTemplate": "/{url}"
"DownstreamHost": "localhost"
"DownstreamPort": "8080"

request-> localhost:5000  
target->localhost:8080 
result  error->404

“/”  not match  ^/[0-9a-zA-Z]*$

I hope this can match Or I'll have to configure it two times

example：
"DownstreamPathTemplate": "/"
"UpstreamPathTemplate": "/"
"DownstreamHost": "localhost"
"DownstreamPort": "8080"

**Comment by TomPallister** [comment]
@cqkisyouq This looks like a bug to me.

For now I would suggest doing having two configurations and I will fix it ASAP! Sorry about this.

Thanks for finding the issue and reporting it! :D

**Comment by TomPallister** [comment]
will close when change is in nuget package.

**Comment by TomPallister** [comment]
@cqkisyouq fixed in https://github.com/TomPallister/Ocelot/releases/tag/2.0.6

**Comment by cqkisyouq** [comment]
@TomPallister Thank you for the change.
But There is a new problem,No placeholder replacement.

This is the last URL of the request:

{Method: GET, RequestUri: 'http://localhost:39343/{url}', Version: 1.1, Content: }

**Comment by cqkisyouq** [comment]
@TomPallister 
because  templateVariableNameAndValues  not find 
 if (urlMatch.Data.Match)
                {
                    var templateVariableNameAndValues = _urlPathPlaceholderNameAndValueFinder.Find(upstreamUrlPath, reRoute.UpstreamPathTemplate.Value);

                    return new OkResponse<DownstreamRoute>(new DownstreamRoute(templateVariableNameAndValues.Data, reRoute));
                }

**Comment by TomPallister** [comment]
@cqkisyouq arghhhhhhh! That’s weird not sure how the tests passed! I will have another look.

**Comment by cqkisyouq** [comment]
@TomPallister 

This is the judgment that has always been false, and it needs to be dealt with in particular.

Class ： 
UrlPathPlaceholderNameAndValueFinder->Find
Arg1->upstreamUrlPath="/"
Arg2->upstreamUrlPathTemplate="/{url}"

if ((upstreamUrlPath.Length > counterForUrl) && CharactersDontMatch(upstreamUrlPathTemplate[counterForTemplate], upstreamUrlPath[counterForUrl]) && ContinueScanningUrl(counterForUrl,upstreamUrlPath.Length))

**Comment by TomPallister** [comment]
@cqkisyouq what is the http request to Oceolot? This seems to be working OK in the acceptance tests.

**Comment by cqkisyouq** [comment]
@TomPallister request url->localhost:5000
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/{url}",
      "DownstreamScheme": "http",
      "DownstreamHost": "localhost",
      "DownstreamPort": 39343,
      "UpstreamPathTemplate": "/{url}",
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 3,
        "DurationOfBreak": 10,
        "TimeoutValue": 5000
      }
    }
  ],

**Comment by TomPallister** [comment]
@cqkisyouq thanks for the help I have replicated the problem. There is an issue with the RoutingTests as well! This is very important to identify so thank you very much!! 

I will start fixing it this morning before work.

**Comment by cqkisyouq** [comment]
@TomPallister Looking at it, it hasn't found a problem yet.

**Comment by TomPallister** [comment]
I might implement this an order of preference for the routing..

This article explains it well http://rion.io/2015/11/13/understanding-routing-precedence-in-asp-net-mvc/

basically if you have /{everything} that will be the lowest priority which means a user can still have specific routes on top of it if they want.

**Comment by TomPallister** [comment]
@cqkisyouq let me know if you find any problems!

**Comment by cqkisyouq** [comment]
Well, thank you for paying attention to this problem.
