### ISSUE TITLE
Monitoring 

### ISSUE THREAD

**Issue by geffzhang** [TomPallister/Ocelot#19]
AppMetrics to achieve performance data acquisition https://github.com/geffzhang/AppMetrics

**Comment by TomPallister** [comment]
@geffzhang after we have service discovery working we can implement these changes. Unless you would like to submit a pull request with the changes you want to make?

**Comment by geffzhang** [comment]
Oh, I do, I still study your code, I am now the first to master the code you write, then I will try to modify, submit the pull request @TomPallister

**Comment by geffzhang** [comment]
I Implement rate limit in #37 ，Please @TomPallister Review my code

**Comment by TomPallister** [comment]
@geffzang rate limiting pull request merged.

**Comment by TomPallister** [comment]
@geffzhang have changed this issue to just Monitoring as you have implemented rate limiting.

**Comment by geffzhang** [comment]
I have used app Metrics to do a demo ocelot demo, can measure the amount of requests, etc., lack of an implementation how to measure each API request monitoring metricshttps://github.com/geffzhang/NanoFabric/commit/794dd398cdc4676f6c2e7e7cc3e58f14539af4c9

**Comment by TomPallister** [comment]
thanks @geffzhang I'll take a look at this!

**Comment by geffzhang** [comment]
measure each API request monitoring metrics use opentracing，This is Pattern: Distributed tracing：
 http://microservices.io/patterns/observability/distributed-tracing.html， I'm trying to use Https://github.com/ButterflyAPM to monitor, which is the code I'm trying to do now https://github.com/geffzhang/Ocelot/tree/Monitoring .

**Comment by geffzhang** [comment]
Monitoring Microservices - A Prediction for 2018： https://www.infoq.com/news/2017/11/monitoring-microservices

**Comment by TomPallister** [comment]
@geffzhang this looks cool! Are you going to create a PR?

**Comment by TomPallister** [comment]
@geffzhang have you looked at Zipkin?

https://zipkin.io/pages/existing_instrumentations.html

**Comment by geffzhang** [comment]
@TomPallister Still exploring, working with ButterflyAPM  the author 。
I have seen Zipkin, more optimistic about Google's Opencensus https://github.com/census-instrumentation

**Comment by geffzhang** [comment]
https://opensource.googleblog.com/2018/01/opencensus.html ButterflyAPM will Support opencensus

**Comment by TomPallister** [comment]
@geffzhang looks very good! :D

**Comment by geffzhang** [comment]
@TomPallister Using Diagnosticsource （https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md）We can define the data points of the trace, we need to discuss the data that needs to be tracked，I've tried to define a few，See https://github.com/geffzhang/Ocelot/blob/Monitoring/src/Ocelot/Tracing/OcelotTracingDiagnosticListener.cs

**Comment by geffzhang** [comment]
This is a blog that I have written that is currently completed in Chinese https://www.cnblogs.com/shanyou/p/8413506.html

**Comment by TomPallister** [comment]
@geffzhang that looks really good! Are you going to submit a PR with the required changes?

**Comment by geffzhang** [comment]
@TomPallister OK, I submit a PR come and look at it together

**Comment by TomPallister** [comment]
@geffzhang awesome thanks! :D

**Comment by geffzhang** [comment]
ButterflyAPM  will support skywalking  https://github.com/OpenSkywalking/skywalking-csharp/pull/1

**Comment by TomPallister** [comment]
@geffzhang very good!!

**Comment by wu-sheng** [comment]
ButterflyAPM is helping Apache SkyWalking to build C#/.NET agent.  Welcome every .NET guys to join us. We want to build a multi-languages distributed tracing and APM system.

**Comment by TomPallister** [comment]
@geffzhang I have merged will do docs and release nuget package asap.

**Comment by TomPallister** [comment]
@geffzhang I am having a problem with Butterfly UI however the solution seems to work and looks very good! :D

https://github.com/ButterflyAPM/butterfly/issues/24

If i have time I will fix it myself.

**Comment by wu-sheng** [comment]
Oh, cool work. Hope after Butterfly team finish our works on Apache SkyWalking compitable c# agent. We can integration with this framework too.

This is . NET part, https://github.com/OpenSkywalking/skywalking-csharp

Our next alpha release looks like a fully functional APM.

https://twitter.com/AsfSkyWalking/status/959213928575254528?ref_src=twcamp%5Ecopy%7Ctwsrc%5Eandroid%7Ctwgr%5Ecopy%7Ctwcon%5E7090%7Ctwterm%5E0 and https://twitter.com/AsfSkyWalking/status/959213652137029632?ref_src=twcamp%5Ecopy%7Ctwsrc%5Eandroid%7Ctwgr%5Ecopy%7Ctwcon%5E7090%7Ctwterm%5E0

**Comment by TomPallister** [comment]
@wu-sheng looks good! :D

**Comment by TomPallister** [comment]
I'm going to close this issue now, please open further issues for functionality around monitoring etc.

OpenTracing is in version 3.0.3!
