### ISSUE TITLE
ReRoutes bug?

### ISSUE THREAD

**Issue by jakey188** [TomPallister/Ocelot#194]
http://localhost:8362/api/user/info?id=1 is ok
http://localhost:3164/api/user/info?id=1 is ok
http://localhost:8330/api/product/info?id=1 is ok
http://localhost:3164/api/product/info?id=1 is 404

is my configuration.json
{
  "ReRoutes": [
  //{
    //  "DownstreamPathTemplate": "/{product}",
    //  "DownstreamScheme": "http",
    //  "UpstreamPathTemplate": "/{product}",
    //  "UpstreamHttpMethod": [ "Get", "Post" ],
    //  "ServiceName": "api-product",
    //  "LoadBalancer": "LeastConnection",
    //  "UseServiceDiscovery": true
    //},
    //{
    //  "DownstreamPathTemplate": "/{user}",
    //  "DownstreamScheme": "http",
    //  "UpstreamPathTemplate": "/{user}",
    //  "UpstreamHttpMethod": [ "Get", "Post" ],
    //  "ServiceName": "api-user",
    //  "LoadBalancer": "LeastConnection",
    //  "UseServiceDiscovery": true
    //},
    {
      "DownstreamPathTemplate": "/api/user/{user}",
      "DownstreamScheme": "http",
      "DownstreamHost": "localhost",
      "DownstreamPort": 8362,
      "UpstreamPathTemplate": "/api/user/{user}",
      "UpstreamHttpMethod": [ "Get" ]
    },
    {
      "DownstreamPathTemplate": "/api/product/{product}",
      "DownstreamScheme": "http",
      "DownstreamHost": "localhost",
      "DownstreamPort": 8330,
      "UpstreamPathTemplate": "//api/product/{product}",
      "UpstreamHttpMethod": [ "Get" ]
    }
  ],
  "GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Host": "localhost",
      "Port": 8500
    }
  }
}

Why is it so? is bug?

**Comment by TomPallister** [comment]
@jakey188 This is a bug with missing validation I think!

I noticed on your configuration for the product re route you have 

_"UpstreamPathTemplate": "//api/product/{product}",_

I think this is causing the problem (have a failing acceptance test for it). 

I think I will add some extra validation that says after the / we must have something valid. I need to check if www.asdf.co.uk//2134 is valid in http :( it probably is!!

**Comment by jakey188** [comment]
@TomPallister Hi!  "UpstreamPathTemplate": "//api/product/{product}"  It's not the key to the problem and I've already proved it ，//api/product/{product} This is due to the error of the hand.

**Comment by TomPallister** [comment]
@jakey188 it worked when I removed the // so I need more information if you are still having trouble :(

**Comment by TomPallister** [comment]
@jakey188 If you turn logging onto Trace cant you send me the logs for when you get a 404?

**Comment by TomPallister** [comment]
@jakey188 I have created a passing test for your scenario you can see it https://github.com/TomPallister/Ocelot/pull/197/files I cant work out why your scenario doesn't work for you!

**Comment by TomPallister** [comment]
@jakey188 also you can try updating to latest ocelot version 2.0.10

**Comment by jakey188** [comment]
@TomPallister my try  updating to latest ocelot version 2.0.10  the problem is solved!

   thank you
