### ISSUE TITLE
Build pipeline improvements

### ISSUE THREAD

**Issue by binarymash** [TomPallister/Ocelot#20]
There's a number of improvements we can make to the build process...

- migrate build scripts to cake to encourage a more formal build pipeline that can also be easily used in AppVeyor
- SemVer versioning
- Cleaning up the nuget feed by publishing unstable builds to a separate feed.
- Hook into the github release process for stable releases, including documentation of what has changed

I have this kind of stuff working on another project, based on how the folks at BDDfy do it as documented at http://www.michael-whelan.net/continuous-delivery-github-cake-gittools-appveyor/ - shouldn't be too much effort to migrate the current bat scripts.

**Comment by TomPallister** [comment]
@binarymash looks good. I'll re read the documentation as a few things I don't quite get yet. Do I need to give you access to AppVeyor?

**Comment by binarymash** [comment]
There will be some changes to the current appveyor config, but lets worry about that once we've got a pull request that you're happy with. For now I'm testing it with my own appveyor project at https://ci.appveyor.com/project/binarymash/ocelot/
