### ISSUE TITLE
May I use load balance in configuration file?

### ISSUE THREAD

**Issue by BowAngel** [TomPallister/Ocelot#201]
Our application is a micro service architecture and there maybe has a facade service between the API gateway and business service, just like this:
![ddddddd](https://user-images.githubusercontent.com/8037477/35033850-22d376b6-fba7-11e7-912d-9a579190b1a2.PNG)

we use facade services to call multiple business services and aggregate results so that each micro service is not dependent on each other.

question:
some business service will have several instances (less than 3) so we need to load balance. I write a class to call business services in the facade service project, and the class reads the Ocelot's config file ("ReRoutes" section) so that the config file doesn't write twice. but it seems that Ocelot only supports to use load balance by using service discovery?  so is there a need to make Ocelot supporting load balance written in the configuration file?

thanks.

**Comment by TomPallister** [comment]
@BowAngel you are correct at the moment Ocelot only load balances when using service discovery. It would be possible to change the file configuration to support reroutes with multiple hosts. 

This isn't something I am planning to do at the moment but I will one day. If you would like to have a go at doing this yourself please do so! Thank you for your interest in the project and your contribution!

**Comment by BowAngel** [comment]
OK, I get it, and I'm glad to do it!

**Comment by TomPallister** [comment]
Lets leave the issue open! I might have a chance to do this soon myself.

**Comment by BowAngel** [comment]
OK, that's a good news! ^_^

**Comment by TomPallister** [comment]
@BowAngel I have PR for this feature. Seems to be working OK. I need to do a bit more work.

**Comment by TomPallister** [comment]
@BowAngel get latest ocelot 3.0.0 and read http://ocelot.readthedocs.io/en/latest/features/routing.html 
http://ocelot.readthedocs.io/en/latest/features/loadbalancer.html

Hope this helps.

**Comment by BowAngel** [comment]
It's very exciting to see that! that's just what I want. I have saw the document link above, and there are two questions:
1. Do I need to set the "LoadBalancer" configuration item when using multiple downstream hosts? if not, what's the default policy? LeastConnection or RoundRobin ?
2. I see the "Catch All" routing has a lower priority than any others. so besides this, other routing still tries to match according to the orders written in the configuration one by one  as the version 2.x?

thanks.

**Comment by TomPallister** [comment]
@BowAngel 

1. You need to set a load balancer it defaults to no load balancer and just uses the first host.
2. Yes it still tries to match one by one. I'm not happy with my code at the moment but thinking about a way to do it nicely.

Thanks! :D
