### ISSUE TITLE
I have a little suggestion about httpclient 

### ISSUE THREAD

**Issue by jakey188** [TomPallister/Ocelot#208]
Hi Tom
I want to have a free record, requesturl,httpmethod,network time consuming
but ocelot not customizable delegatinghandler
i want to httpclient more flexible. i will be in delegatinghandler do more anything
Is it possible to consider the implementation

**Comment by TomPallister** [comment]
@jakey188 

I do not understand fully what you want to do.

At the moment I do not plan to change how the HttpClient works! 

However you can do whatever you want with Ocleot because all of its service are registered with TryAdd which means if you have already added the interface and implementation .net will not try to do it again.

This means that you can override any of the services. 

IHttpRequester is responsible for returning the HttpResponseMessage to the Ocelot pipeline. Therefore you can provide your own implementation of this interface and register is before adding the ocelot services.

e.g.

```csharp
services.AddJakeyHttpClient();
services.AddOcelot();
```

Alternatively if you want to contribute to Ocelot you could change HttpClientHttpRequester to take IHttpClientBuilder as a dependency and rather than new up HttpClientBuilder and override this.

I hope this helps.

**Comment by jakey188** [comment]
@TomPallister 
I want to record all the request http information.
`public class HttpTracingDelegatingHandler : DelegatingHandler
    {
        
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var method =  request.Method;
            var requestUrl = request.RequestUri.ToString();
            //db.Save(method,requestUrl);
            //or do some other things
            return base.SendAsync(request, cancellationToken);
        }
    }`

now I need to take HttpTracingDelegatingHandler join in HttpClient 

 var _handlers = new Dictionary<int, Func<DelegatingHandler>>();
                _handlers.Add(1000, () => new HttpTracingDelegatingHandler());
                HttpMessageHandler httpMessageHandler = new HttpClientHandler(); 
                _handlers
                .OrderByDescending(handler => handler.Key)
                .Select(handler => handler.Value)
                .Reverse()
                .ToList()
                .ForEach(handler =>
                {
                    var delegatingHandler = handler();
                    delegatingHandler.InnerHandler = httpMessageHandler;
                    httpMessageHandler = delegatingHandler;
                });
                return new HttpClient(httpMessageHandler);

**Comment by jakey188** [comment]
I need http tracing . including all services and ocelot

**Comment by TomPallister** [comment]
@jakey188 OK we might be able to expose the handlers dictionary? I can have a look at this at some point in the future.

However if you need tracing @geffzhang is looking into using distributed tracing butterfly in this issue https://github.com/TomPallister/Ocelot/issues/19 so that might be better?

**Comment by jakey188** [comment]
yes ,we might be able to expose the handlers dictionary for use butterfly .

**Comment by geffzhang** [comment]
@jakey188I have added Httptracingdelegatinghandler https://github.com/geffzhang/Ocelot/blob/Monitoring/src/Ocelot/Tracing/OcelotHttpTracingHandler.cs , have basically completed and butterfly integration work, but there are test work and ocelot tracing buried point work to do, we can together to improve。 We are mainly  here #19  to discuss this work

**Comment by TomPallister** [comment]
@jakey188 please look at https://github.com/TomPallister/Ocelot/pull/224 this is my idea to implement your request. DelegatingHandlers now exposed...

```csharp
s.AddOcelot()
                    .AddDelegatingHandler(() => new FakeHandler())
                    .AddDelegatingHandler(() => new FakeHandler());
```

The delegating handlers are run in order of addition so FIFO if you are using QoS feature of Ocelot that will always be last.

Let me know if you have any suggestions.

**Comment by jakey188** [comment]
thanks very much . expect you to incorporate the code into the trunk

**Comment by TomPallister** [comment]
cool I will merge it soon

**Comment by TomPallister** [comment]
This functionality is in version 3.0.3
