### ISSUE TITLE
how to Administration support cors

### ISSUE THREAD

**Issue by ICE2017** [TomPallister/Ocelot#210]
```
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddCors(options =>
            {
                options.AddPolicy("CorsPolicy",
                builder => builder.AllowAnyOrigin()
                .AllowAnyMethod()
                .AllowAnyHeader()
                .AllowCredentials());
            });
            services.AddOcelot(Configuration)
                .AddAdministration("/administration", "832ff5f28ef5b5a3");
        }

        public  void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseCors("CorsPolicy");
            app.UseOcelot();
        }
```

```
Failed to load http://service.yfgt.com/administration/configuration: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access. The response had HTTP status code 500.
```  
I AllowAnyOrigin but when i request administration，it did not work ?

**Comment by TomPallister** [comment]
@ICE2017 Thank you for your interest in the project!

Please have a look at previous issue https://github.com/TomPallister/Ocelot/issues/191 this might help.

If you are still having problems let me know and I will look into it more.

**Comment by ICE2017** [comment]
@TomPallister thanks very much, i set CORS like #191 .but when i GET http://localhost/administration/configuration  it did not work,but POST http://localhost/administration/connect/token works well.  
![1](https://user-images.githubusercontent.com/12882373/35654483-50520a12-0728-11e8-8654-badea6e00c16.png)
![2](https://user-images.githubusercontent.com/12882373/35654484-508254e2-0728-11e8-849f-4886fe3d5438.png)
what's going wrong?

**Comment by TomPallister** [comment]
@ICE2017 can you paste your configuration.json file here please?

**Comment by TomPallister** [comment]
@ICE2017 also if you turn logging on what errors do you see?

**Comment by ICE2017** [comment]
@TomPallister  thank a lot ! i try the exception 
when i set url like this .UseUrls("http://*:5000"); it did not work,i changed .UseUrls("http://localhost:5000"); it work well. then exception like this 
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLB9A19MLRHC", Request id "0HLB9A19MLRHC:00000002": An unhandled exception was thrown by the application.
System.InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://*:80/administration/.well-known/openid-configuration'. ---> System.IO.IOException: IDX10804: Unable to retrieve document from: 'http://*:80/administration/.well-known/openid-configuration'. ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
```
thanks very much

**Comment by TomPallister** [comment]
@ICE2017 interesting this is because the administration section uses IdentityServer for authentication. IdentityServer requires that you set an authority that issues the tokens.

See this issue https://github.com/IdentityServer/IdentityServer4/issues/1207

I think that you will need to run Ocelot with a specific URL when using the administration section at the moment. I will think about this and see if there is a solution!
