### ISSUE TITLE
I can't build ocelot on .net core sdk 2.1.4 

### ISSUE THREAD

**Issue by JamesYing** [TomPallister/Ocelot#217]
Hi bro,
Below is my build env:
VM - windows 7-64bit
vs2017
sdk: net core 2.1.4
runtime:.net core 2.0
I got the latest version from github. When I build it, the vs2017 return below error:
The current .NET SDK does not support targeting .NET Core 2.0.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.0.

I mark sure I installed it on my book.

**Comment by TomPallister** [comment]
@JamesYing thanks for your interest in the project!

Can you build any other .net core 2.0 projects?

**Comment by JamesYing** [comment]
@TomPallister 
Hi， Thanks for your answer.
Yes, I can build other .net core 2.0 project. And when I create a new solution and add ocelot.csproj，it's well.

Would you like to check the .sln file?

**Comment by TomPallister** [comment]
@JamesYing if you can work out what the problem is and create a pull request that would be awesome!

If not I will have a look at it asap.

**Comment by JamesYing** [comment]
@TomPallister 
hi Tom,I tried several times and found that it was a build.ps1 file has problem,  when I deleted the file, the project could be build.            
But I don't know much about PowerShell So I can't help you modify it .
Could you check it ?

**Comment by TomPallister** [comment]
@JamesYing build.ps1 is from the cake framework. It might need updating but this seems very strange!

**Comment by JamesYing** [comment]
@TomPallister 
Hi Tom, I found the problem from the build.ps1, I get the latest build.ps1 on your project and I rebuild it, Now it's fine.
And the sdk version is 2.0.2 in global.json file, so I changed it to 2.1.4 by myself.

You can close this issue and Thanks for your help!

**Comment by TomPallister** [comment]
@JamesYing I will fix in develop before I close!

**Comment by TomPallister** [comment]
I have updated the build.ps1 on develop...will not upgrade sdk yet..but soon.
