### ISSUE TITLE
How can I redirect a request only if it brings a JWT CORRECT?

### ISSUE THREAD

**Issue by FerAguilarR93** [TomPallister/Ocelot#220]
When I'm going to perform a user login I need to not validate a jwt since it is public domain, however if I want to register a user I need to have the jwt and that this is correct, otherwise I will not redirect it ... Is this possible from the configuration file?
Thanks in advance

**Comment by TomPallister** [comment]
@FernandoAguilarResendiz please read the docs here http://ocelot.readthedocs.io/en/latest/features/authentication.html and see if that helps you. 

All Ocelot does is calls whatever authentication provider you have registered!
