### ISSUE TITLE
[CONTACT] Using Ocelot in Microsoft Reference Application for Microservices

### ISSUE THREAD

**Issue by CESARDELATORRE** [TomPallister/Ocelot#229]
Hey Tom!
This is Cesar de la Torre, PM at the .NET team.
You might be aware of our [guidance/book](https://aka.ms/microservicesebook) about microservices and its related reference application, [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers).
We were covering API Gateways in the guide/book, but not in the sample application, yet. 
But now, we're currently implementing API Gateways for it based on Ocelot, as we find it a good .NET Core based API Gateway, flexible enough, light/lean and OSS. It is still in development, though, still not in the by default branch of eShopOnContainers sample app.

I just wanted to contact you to let you know about it and also to contact your through email so we can discuss more about it, ok?
Please, send me an email to cesardl at Microsoft.com , ok?
Thanks,

**Comment by TomPallister** [comment]
@CESARDELATORRE wow that’s is really cool! I am aware of the book and application. I will email you ASAP.

**Comment by geffzhang** [comment]
that is really cool

**Comment by CESARDELATORRE** [comment]
Yep!, I got you email! Let's sync when possible! :)

**Comment by TomPallister** [comment]
Excellent I will reply ASAP!
