### ISSUE TITLE
OcelotBaseUrl should be configuration

### ISSUE THREAD

**Issue by geffzhang** [TomPallister/Ocelot#233]
http://ocelot.readthedocs.io/en/latest/introduction/gettingstarted.html#addocelotbaseurl is not configurable and can be configured to read？ I see use MemoryConfigurationSource

**Comment by TomPallister** [comment]
@geffzhang do you mean in configuration.json? I did try it this way but was not sure as configuration can be changed during runtime. However you would not be able to change a url during runtime.

**Comment by TomPallister** [comment]
@geffzhang actually i have thought about this more and maybe you can! Do you think I should move it into configuration.json?
