### ISSUE TITLE
Can the configuration file be modified once the service is running?

### ISSUE THREAD

**Issue by FerAguilarR93** [TomPallister/Ocelot#235]
Hello, I have a question ... if I have running the Gateway API and I need to add another host to the configuration file, is there any way to do it without stopping the application?

**Comment by TomPallister** [comment]
@FerAguilarR93 yes you can use the administration API

http://ocelot.readthedocs.io/en/latest/features/administration.html

Let me know if you have any questions. It's not a great API but work...ish :)
