### ISSUE TITLE
Upgrade to VS 2017

### ISSUE THREAD

**Issue by geffzhang** [TomPallister/Ocelot#32]
Vs2017 has released RC4 release [Announcing .NET Core Tools Updates in VS 2017 RC](https://blogs.msdn.microsoft.com/dotnet/2017/02/07/announcing-net-core-tools-updates-in-vs-2017-rc/) ，NET core tooling also RC, we upgrade to the VS2017 project to develop it?

**Comment by binarymash** [comment]
I expect this will require changes to the cake build scripts. It will also require changes to the AppVeyor projects to use the VS2017 image. This appveyor image isn't public yet, but they do have a private beta of the RC - you can request access for an appveyor account at https://github.com/appveyor/ci/issues/1179

**Comment by TomPallister** [comment]
@geffzhang we will start looking into this after 07/03/2017 when VS 2017 is released.
