### ISSUE TITLE
Better logging / Check logging

### ISSUE THREAD

**Issue by TomPallister** [TomPallister/Ocelot#35]

**Comment by TomPallister** [comment]
its probably a bit rubbish :(

**Comment by MarcDenman** [comment]
Any hints/suggestions for this? Are there any areas that need a bit more logging than others?

Ocelot looks a lot like something I had been to toying with about 6 months ago except far far better! Probably going to look at the codebase other the weekend so quite happy to start looking at improving the logging if that would be helpful.

**Comment by TomPallister** [comment]
@MarcDenman when I started writing Ocelot I wrote a wrapper around the standard .NET core logging stack for some reason and I can't really remember now which is not good! It might have been because I wanted to allow the user to specify a request id / correlation id that their requests should log to rather than the .NET request id stuff. 

Thinking about this I'm not really happy with how all that worked so I was going to review it and see if the code could be improved.

There is also an issue where some places take a logger factory and create a new logger in the constructor and other places where we pass a logger in. I would probably favour doing the same thing everywhere as it avoids confusion.

Also all the logging statements are directly in code that they are logging about and I was thinking about using the decorator pattern to move the logging out of the class doing logic.

Finally the log messages are pretty sporadic. I would just like to organise it. 

I know how important good logging is and I'm annoyed at myself for letting it slip a bit.

Any help would be appreciated.

**Comment by MarcDenman** [comment]
@TomPallister That is brilliant information, thank you :) 

Unless you have any huge objections, I am going to start by trying to get all the logging injection consistent (probably using the `IOcelotLoggerFactory` for now) and just make sure there are logging statements in all the right places. 

Hopefully after that any refactoring for the wrapper will be a little bit easier.

**Comment by MarcDenman** [comment]
Just made a [commit ](https://github.com/TomPallister/Ocelot/commit/3fb83077fb8e9f27d76a69c47003df35c7955103) for some changes to the responderMiddleware. 

I know it is only a little change but could someone double check and make sure it is roughly what was wanted, didn't realise there were so many middlewares and don't want to get halfway through before realising I have gone down the wrong track.

I am also going to expand the `IOcelotLogger` to also implement LogTrace to try and give a little bit more granularity.

**Comment by TomPallister** [comment]
@MarcDenman I've left a comment on the commits, let me know what you think.

**Comment by MarcDenman** [comment]
Sorry, meant to reply yesterday but forgot. Your comment sounds good, I have added a prop on the Base OcelotMiddelware class which sets the name when it is initialised. 

I have just pushed some more changes up, I will probably turn that into a PR tomorrow and then in a couple days time do another with a few more changes, save the PR getting too huge.

**Comment by TomPallister** [comment]
@MarcDenman sounds like a good idea, looking forward to it.
