### ISSUE TITLE
Update Ocelot configuration without downtime

### ISSUE THREAD

**Issue by TomPallister** [TomPallister/Ocelot#36]
At the moment if you want to update ocelot configuration you need to edit configuration.json and restart the service. I guess if you are deploying Ocelot with docker containers updating one and throwing away the others is a viable strategy but where I work we would probably not do this.

I would like it so that you can update the configuration with no downtime. Probably going to add an API that be accessed over HTTP to do this. 

I imagine the API would ultimately update configuration.json and reload the static config in memory. It will probably be fine to create the updated version in memory, lock the existing one, update it and release the lock. Should be pretty fast and not cause anyone problems.

Clients could be a CLI tool, web app etc

Concerns are mainly authentication / authorisation. Also user would need to specific some kind of api path that they would never map any routes to..in app.UseOcelot we could do a builder.Map("/someadminroute", etc) this means any requests that have the route in would go to the api.

There could be a section in configuration.json that says who can access endpoints and how they are authenticated. I really don't want to write my own authentication / authorisation code however would ideally like to do this with no dependencies which is going to make it hard. When I say dependencies I mean SQL Server for storing users etc.

Could potentially make Ocelot use IdenityServer and bearer tokens and make identity server look at configuration.json for users, claims, scopes etc. Even simpler when bootstrapping identity server you could use in memory implementation and load everything out of configuration.json. Problem then is if you expose endpoints to change authenticated users / authorization stuff how would you rebootstrap identity server.

After this is working for one deployed Ocelot instance the next step is some kind of clustering that keeps the config up to date among all Ocelots!

**Comment by geffzhang** [comment]
Online updates to ReRoute, needs to have a unique identity that exists in the code ReRouteKey identifies the ReRoute is now used for load balancing, it is a calculated value, I think there should be certain identification value, similar to a database table's primary key, so that we can store  ReRoute in database or Consul, it will be great storage across servers and updates In this case the local profile can be a backup of the currently running.

**Comment by TomPallister** [comment]
@geffzhang first iteration I do not want to use any dependencies such as consul or database. I try to take a lean approach to software development and use dependencies only when I have to.

UpstreamPathTemplate and UpstreamHttpMethod must be unique in Ocelot so we do not need a specific key such as GUID.

My plan is to expose API that lets you post entire configuration and reload it. I know that this is a hack but I want to make sure authentication is in place before we start looking at better ways to do this. When I have something basic working I will make it better.

Then I will make cluster of Ocelots that keep configuration up to date across cluster.

Finally I will make Ocelot into service discovery so services can register with Ocelot. 

All of these features will be behind interface so a user can swap them out and use a database/consul etc if they want to.
