### ISSUE TITLE
Look at code coverage integration

### ISSUE THREAD

**Issue by TomPallister** [TomPallister/Ocelot#40]
Look at coveralls integration might be able to get code coverage stats

**Comment by binarymash** [comment]
I have this running now one one of my repos... uses opencover to generate the report, and report generator to build a nice html report, and fails the build if coverage falls below a certain level. If you're running on the build server it also uploads to coveralls.io. 

Have a look at https://github.com/binarymash/responses/pull/28 and https://coveralls.io/github/binarymash/responses

Happy to pick this up when I have a moment.

**Comment by binarymash** [comment]
work in progress.... https://coveralls.io/github/binarymash/Ocelot  :)

you'll need to create an environment variable on the appveryor build, 'coveralls-repo-token-ocelot', which contains the coveralls repo key for https://coveralls.io/github/TomPallister/Ocelot. This is a private key so we shouldnt commit it to the repo.

I'm not going to create a pull request yet, cos most of this work is a cut and paste job from my repo so not sure if it's 100% correct... going to let things stew for a few days. Could probably at least  optimise the build process as I think it's currently compiling the same things several times.

**Comment by TomPallister** [comment]
@binarymash looks cool!!! Will have to have a go at this when I get a chance. Probably not going to be until June. You have write access on this repo btw so you can be the boss while im away if you want!

**Comment by binarymash** [comment]
The links above are for the code on my branch, so there shouldn't be anything you need to do once I've created the PR other than review it (and set the environment variable in AppVeyor).

Not sure I've got the time to look after everything while you're away, but I'll keep an eye on things. When are you off?

**Comment by binarymash** [comment]
Merged in 1.5.0-unstable.79.build.199
