### ISSUE TITLE
Get Cake build working on MacOS

### ISSUE THREAD

**Issue by TomPallister** [TomPallister/Ocelot#41]
Think the problem is that cake cannot reference variables declared at top of page in private methods on macos...no idea why it can on windows!

**Comment by binarymash** [comment]
Had the same problem when trying to set stuff up on my own project, and got it working... I'll pick this up now.

**Comment by TomPallister** [comment]
@binarymash thanks! I spent ages trying to work this out so very interested in why it didn't just work.

**Comment by binarymash** [comment]
I don't understand the difference between Mac and Windows, but the variables can be accessed from all the tasks so the solution is just to pass them into the private methods.

**Comment by TomPallister** [comment]
Sounds good! I'm a bit embarrassed I didn't try that!
