### ISSUE TITLE
HTTPS request error

### ISSUE THREAD

**Issue by kingreatwill** [TomPallister/Ocelot#46]
![image](https://cloud.githubusercontent.com/assets/13087689/23054787/f3962718-f51c-11e6-80c0-2b59e09e0f38.png)
![image](https://cloud.githubusercontent.com/assets/13087689/23054802/0d771714-f51d-11e6-8d16-23644b564717.png)

**Comment by TomPallister** [comment]
@kingreatwill please check https://localhost/planapi/api/plan/test SSL certificate is valid. Ocelot will not allow requests to invalid SSL. This is controlled by .NET framework.

If you pull latest develop and run Ocelot.ManualTest application, request url http://localhost:5000/posts this will connect to remote server over https.
