### ISSUE TITLE
Documentation for rate limiting

### ISSUE THREAD

**Issue by TomPallister** [TomPallister/Ocelot#48]

**Comment by catcherwong** [comment]
I wrote a simple blog that introduce how to use rate limiting in Ocelot.

[Building API Gateway Using Ocelot In ASP.NET Core - Rate Limiting - Part Four](http://www.c-sharpcorner.com/article/building-api-gateway-using-ocelot-in-asp-net-core-rate-limiting-part-four/)

**Comment by TomPallister** [comment]
@catcherwong wow that is amazing!!!! Thank you very much for your interest and help with the project.

I will use this as a basic for the documentation!! I will put a link to your posts as well.

Thank you!!!!!!!!!!

**Comment by icebergdelphi** [comment]
Hi guys, it is possible to establish RateLimiter by ClientId from DataBase?, I mean, for example, I have a database with 1000 clients so what I need is set a different rate limit for every client from my database.
I understand that Ocelot config.json has the value ClientIdHeader, but I would like to do it dynamically.

Thank you.

**Comment by GarethBalfour** [comment]
@icebergdelphi did you get anywhere with the request above?
