### ISSUE TITLE
Find a replacement for TestConfiguration.cs

### ISSUE THREAD

**Issue by binarymash** [TomPallister/Ocelot#50]
The acceptance tests rely on TestConfiguration to get the path to the configuration file used by the tests. This causes a couple of problems...

1. The build configuration is hard-coded to debug
2. It currently fails if you are using osx.10.12-x64.

We should be able to replace this with dynamic code that calculates the config file path dynamically. Surely we can do something like 

```csharp
using System.IO;

\\...

return Path.Combine(Directory.GetCurrentDirectory(), "configuration.json");
```

**Comment by TomPallister** [comment]
@binarymash yeh I don't even know why i did this. Can only assume my brain left my head.

I've changed it on the branch I'm working on at the moment.
