### ISSUE TITLE
Get the readme into read the docs style

### ISSUE THREAD

**Issue by TomPallister** [TomPallister/Ocelot#51]
No idea how to do this but would be nice

https://readthedocs.org/

**Comment by geffzhang** [comment]
There are docfx http://cakebuild.net/dsl/docfx/

**Comment by TomPallister** [comment]
@geffzhang does doxfx work with mac osx? It doesnt seem to be cross platform.

**Comment by geffzhang** [comment]
I Add ocelot to awesome-dotnet-core https://github.com/thangchung/awesome-dotnet-core/pull/75

**Comment by TomPallister** [comment]
@geffzhang thank you!!

**Comment by TomPallister** [comment]
Have decided to use github wiki here https://github.com/TomPallister/Ocelot/wiki
