### ISSUE TITLE
Cluster of Ocelots when you update one it updates them all

### ISSUE THREAD

**Issue by TomPallister** [TomPallister/Ocelot#55]
started working on this probably going to try and use raft consensus to keep cluster up to date.

**Comment by geffzhang** [comment]
use raft consensus to keep cluster ，This feature is great

**Comment by TomPallister** [comment]
@geffzhang yes this is what I am going to use.

**Comment by TomPallister** [comment]
Small update i have been working on this but nothing to push yet, raft is very hard :) but i have a cluster starting and electing a leader!

**Comment by geffzhang** [comment]
Come on, we are very much looking forward to this feature

**Comment by TomPallister** [comment]
@geffzhang 👍  it is nearly finished!

**Comment by TomPallister** [comment]
_Short update_

Features Working

- Leader election
- Log replication
- New election after election timeout 
- Add new server to active cluster

Not working

- Log replication after new leader election - bug in my code
- Forward commands from nodes to leader - should be easy
- Add new server to active cluster and all logs are replicated - havent tested this yet.

**Comment by geffzhang** [comment]
@TomPallister  pull your newest code  ,I am learning to test together

**Comment by TomPallister** [comment]
@geffzhang I have invited you to the repository..I'm doing it in a separate project at the moment. Ocelot will take a dependency on raft implementation rather than code being in Ocleot project.

**Comment by TomPallister** [comment]
@geffzhang the raft implementation can be found at https://github.com/TomPallister/Rafty I will work on this package seperately and Ocelot will use it as a dependency to agree on configuration values across a cluster. This also means Ocelot can now be a service discovery provider.

The code in Rafty is not very good. I build this really quickly just to try and get something working. I intend to improve it over time.

**Comment by geffzhang** [comment]
@TomPallister This is awesome

**Comment by MichaCo** [comment]
Hi @TomPallister, maybe a stupid question, but, why can you not use existing service discovery and key/value servers/tools, like Consul for example?
All this stuff is not easy to build and, more importantly, to test and get right. Just wondering what the motivation is to roll your own.

**Comment by TomPallister** [comment]
@MichaCo I agree :(

**Comment by MichaCo** [comment]
@TomPallister yup, learning those things is totally cool ofc :)

**Comment by TomPallister** [comment]
Because of the abstractions around getting and setting the Ocelot config I think its pretty trivial to persist it in Consuls KVP store. I might can this PR for a little while and work on that instead.

**Comment by TomPallister** [comment]
@MichaCo i have just merged a PR that lets you use Consul KV store as persistence for the Ocelot configuration. Was pretty rushed but acceptance test for it passed so should work. Im going to leave this open as I would like to work on the raft feature when I have the time!

**Comment by MarcDenman** [comment]
@TomPallister Unrelated but thought it might be useful for you [https://twitter.com/aphyr/status/854909543255613440 ](https://twitter.com/aphyr/status/854909543255613440 ) - A nice little tool for testing raft implementations!

**Comment by TomPallister** [comment]
@MarcDenman looks good thanks, My raft implementation is ready now..i think..

**Comment by rocketRobin** [comment]
Nice!

**Comment by TomPallister** [comment]
forgot to close this when i merged raft
