### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by jsantanainel** [TomPallister/Ocelot#60]
Hi, I was looking for about a Gateway for .NET for a long time. I´m very happy for found your project. I´m going to study the documentation and try to put in practice. 

Do you have plans to continue this project?

Thanks for your time.

**Comment by TomPallister** [comment]
@jsantanainel thanks for appreciating the effort! 

I do intend to keep working on the project. It is very early days so the code isn't amazing yet. I think there are a lot more features to add and a lot of refactoring to do before it is a good product.

The next thing I'm working on is some kind of clustering so you can have multiple instances deployed and they keep themselves updated when you make config changes.
