### ISSUE TITLE
dotnet core SDK1.0.1 build error

### ISSUE THREAD

**Issue by zhangzenan** [TomPallister/Ocelot#65]
![image](https://cloud.githubusercontent.com/assets/16860235/23782086/b6c05d88-058c-11e7-9061-375db8cfec0a.png)

**Comment by TomPallister** [comment]
@zhangzenan please download and install runtime and SDK here  https://www.microsoft.com/net/download/core#/runtime

**Comment by TomPallister** [comment]
@zhangzenan this will work now as I have upgraded to VS 2017.

**Comment by zhangzenan** [comment]
Thank you,I have build success.






At 2017-03-12 22:25:47, "Tom Pallister" <notifications@github.com> wrote:


@zhangzenan this will work now as I have upgraded to VS 2017.
