### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by FryDerm** [TomPallister/Ocelot#68]
This may be a little nit-picky, but why are you renaming ApiName (in identity server) to ScopeName (ocelot)?  The same goes for AllowedScopes (identity server) to AdditionalScopes (ocelot)?

**Comment by TomPallister** [comment]
@FryDerm In a previous version of identityserver they were scopename and additionalscopes and I haven't changed it yet. Would happily accept a PR for this.

**Comment by FryDerm** [comment]
I'll get on it.  Happy to help you.

**Comment by TomPallister** [comment]
@FryDerm just merged PR to fix this forgot to tag this issue.
