### ISSUE TITLE
Ocelot's overall performance is not very good

### ISSUE THREAD

**Issue by geffzhang** [TomPallister/Ocelot#73]
Here we used Apache Bench performance in a simple test. We simulated 1000 users, 100 requests, the following are test results, configuration of the machine is CPU:Intel i5 2 nuclear, 4G memory test on the machine:
D:\Workshop\ab>ab.exe -n 1000 -c 100 http://localhost:5000/api/values/
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests

Server Software: Kestrel
Server Hostname: localhost
Server Port: 5000

Document Path: /api/values/
Document Length: 19 bytes

Concurrency Level: 100
Time taken for tests: 7.880 seconds
Complete requests: 1000
Failed requests: 0
Total transferred: 178000 bytes
HTML transferred: 19000 bytes
Requests per second: 126.90 [#/sec] (mean)
Time per request: 788.013 [ms] (mean)
Time per request: 7.880 [ms] (mean, across all concurrent requests)
Transfer rate: 22.06 [Kbytes/sec] received

Connection Times (ms)
min mean[+/-sd] median max
Connect: 0 0 0.4 0 2
Processing: 349 758 239.5 672 1800
Waiting: 349 758 239.4 672 1800
Total: 349 758 239.4 672 1801

Percentage of the requests served within a certain time (ms)
50% 672
66% 701
75% 738
80% 748
90% 1063
95% 1457
98% 1653
99% 1717
100% 1801 (longest request)
Average number of requests per second (throughput) to 126.90, judging by the number of requests from different distributions, response time is also more stable than direct access interface performance decreases sharply, a difference of 30 times.
ab.exe -n 1000 -c 100 http://localhost:9030/api/values/
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests

Server Software: Kestrel
Server Hostname: localhost
Server Port: 9030

Document Path: /api/values/
Document Length: 19 bytes

Concurrency Level: 100
Time taken for tests: 0.297 seconds
Complete requests: 1000
Failed requests: 0
Total transferred: 158000 bytes
HTML transferred: 19000 bytes
Requests per second: 3367.05 [#/sec] (mean)
Time per request: 29.700 [ms] (mean)
Time per request: 0.297 [ms] (mean, across all concurrent requests)
Transfer rate: 519.53 [Kbytes/sec] received

Connection Times (ms)
min mean[+/-sd] median max
Connect: 0 0 0.3 0 1
Processing: 0 28 18.7 18 75
Waiting: 0 25 18.8 15 65
Total: 0 28 18.7 18 75

Percentage of the requests served within a certain time (ms)
50% 18
66% 39
75% 47
80% 49
90% 54
95% 59
98% 64
99% 65
100% 75 (longest request)

**Comment by geffzhang** [comment]
The performance should come from the HttpClient, how to optimize is a big problem

**Comment by TomPallister** [comment]
@geffzhang Can you describe the system under test?

Was Apache Bench running on the same machine as Ocelot? Was the downstream service running on the same machine as Ocelot? 

To confirm the results above show making a call to a downstream service proxying via Ocelot (http://localhost:5000/api/values/) and then directly to the downstream service  ( http://localhost:9030/api/values/) without Ocelot?

Did you do any profiling while the test was running to see what is causing the issue?

When writing Ocelot I haven't really considered performance yet. I am aware that it could be a problem!

Thanks ! 👍

**Comment by geffzhang** [comment]
yes ，on the same machine ，my test project in https://github.com/geffzhang/NanoFabric/ .  http://localhost:9030/api/values/ is   https://github.com/geffzhang/NanoFabric/blob/develop/sample/SampleService.Kestrel
and http://localhost:5000/api/values/ ocelot is https://github.com/geffzhang/NanoFabric/tree/develop/src/NanoFabric.Ocelot 
 14 days ago I pull a requests https://github.com/TomPallister/Ocelot/pull/57

**Comment by geffzhang** [comment]
Reference code https://github.com/aspnet/Proxy

**Comment by TomPallister** [comment]
@geffzhang what logger level are you using in Ocelot when running the performance test?

I had the same results as you and using JetBrains dotTrace I can see the issue was with the logging level. When I set the logging to Error level only the performance was almost equal to testing downstream 

Ocelot
Requests per second:    93.68 [#/sec] (mean)
Time per request:       1067.508 [ms] (mean)
Time per request:       10.675 [ms] (mean, across all concurrent requests)
Transfer rate:          16.28 [Kbytes/sec] received

Downstream Service
Requests per second:    104.90 [#/sec] (mean)
Time per request:       953.332 [ms] (mean)
Time per request:       9.533 [ms] (mean, across all concurrent requests)
Transfer rate:          16.19 [Kbytes/sec] received

Can you test this please?

**Comment by geffzhang** [comment]
@TomPallister logger level is Info， I Change logger level to error is the same to you ,Log the performance impact so large

**Comment by VeritasSoftware** [comment]
Hi,

My API Gateway framework, design & source code, 
has recently been on-boarded by the .NET Foundation.

Project link:  https://github.com/VeritasSoftware/AspNetCore.ApiGateway
On-boarding link:  https://github.com/dotnet-foundation/projects/issues/255

My design envisages the Gateway as a microservice. 
It uses the Asp Net Core request pipeline.

Ocelot, has a whole different request pipeline.

So, how do you think it will compare against Ocelot,
performance wise?

**Comment by raman-m** [comment]
@VeritasSoftware
You live in India. Why did you specify Australia as your residence location? 
Ask your question in [Discussions](../discussions)!
