### ISSUE TITLE
not support two parameter？

### ISSUE THREAD

**Issue by maradonasu** [TomPallister/Ocelot#74]
in my **configuration.json**
```
"ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/{customerid}/project/{id}",
      "DownstreamScheme": "http",
      "DownstreamPort": 5000,
      "DownstreamHost": "localhost",
      "UpstreamPathTemplate": "/{customerid}/project/{id}",
      "UpstreamHttpMethod": "Delete",
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 3,
        "DurationOfBreak": 10,
        "TimeoutValue": 5000
      }
    }]
```
my request  **url**
`HTTP/1.1 DELETE  http://apigatway/701/Project/1`

my api server get request 
`HTTP/1.1 DELETE http://localhost:5000/api/701/project/%7Bid%7D`

the second parameter {id} value was not find。

**Comment by TomPallister** [comment]
@maradonasu that should work. I will test this when I get a chance. 

Maybe try the config with a trailing / after the {id} parameter, if that works then there is a bug.

These tests cover your scenario if you would like to investigate this yourself. 

UpstreamUrlPathTemplateVariableReplacerTests.cs
RoutingTests.cs

This is the class most likely to have a bug

UrlPathPlaceholderNameAndValueFinder.cs

**Comment by maradonasu** [comment]
I try the config with a trailing / after the {id} parameter, it's not work
