### ISSUE TITLE
Hierarchial Configuration 

### ISSUE THREAD

**Issue by abdulkaderjeelani** [TomPallister/Ocelot#77]
Hi Tom,
Congrats and thanks for your good initiative. 
IMHO, As the intention is to provide a gateway for MicroServices we shall split the reroute configuration. 
New  MicroService level configuration or Downstream host level configuration, here we shall have the Authentication part.  we use identity server to protect our client API,  Instead of specifying this for each route we shall specify at top level. 
A wild card mapping will be a lot interesting as well. 

Waiting to hear from you, will send a pull request soon.  Cheers

**Comment by TomPallister** [comment]
@abdulkaderjeelani Sounds good, when you do the pull request please do not break existing ways of configuring Ocelot. It need to support many configuration methods!
