### ISSUE TITLE
Is it production ready? Distribution and hosting options.

### ISSUE THREAD

**Issue by kuncevic** [TomPallister/Ocelot#83]
1. Is Ocelot is production ready?
2. If so, are you guys using docker containers to distribute your .net core solutions with Ocelot?
3. Are you using Azure, AWS, Linux VM or something else?

p.s
Just thinking to go with .net core for my next project and currently in research mode thinking about the architecture, distribution and hosting options, etc.

**Comment by TomPallister** [comment]
@kuncevic 

1. I can't say if it is production ready yet. I would like to use it where I work but we need something from NET Standard 2.0 which has not been released yet. When this is released I'm hoping where I work would be interested in trying Ocleot out.

2. I am using docker but haven't put up an image yet.

3. You can use anything to host your containers, Azure, AWS, VMs etc are all fine.

**Comment by kuncevic** [comment]
I would like to try it out at some point soon. Form the description it is sounds like it is handles the IdentityServer tokens which is making a lot of sense as I am already using IdentityServer.

What exactly it is missing from NET Standard 2.0? Can you give a bit more light on that?

**Comment by geffzhang** [comment]
@kuncevic I have applied it to the product environment, in the process of using ocelot to improve the functional characteristics

**Comment by TomPallister** [comment]
@kuncevic at my work we would need a custom middleware injected into Ocelot that uses something from .NET Standard 2.0. I cant really say what it is as work related and not sure if Im allowed!
