### ISSUE TITLE
Path Prefix

### ISSUE THREAD

**Issue by danny-waite** [TomPallister/Ocelot#86]
Hi Tom, I'm in the process of evaluating Ocelot, looks great, nice work.  In my architecture I have several microservices each with their own REST API, some simple, some more complex.  I looks like in Ocelot I have to define each HTTP request I want to map, which doesn't feel right and would add quite a lot of development overhead.  Traefik for example supports a PathPrefix, can this kind of thing be done with Ocelot or have I misunderstood it's concept?

**Comment by TomPallister** [comment]
@danny-waite I had a look at that pathprefix and tbh didn't really get it :( I can be a bit stupid. Could you explain to me exactly what you want to do?

I'm thinking rather than defining all your incoming requests with the API gateway you want to have some kind of easy to define convention that just works for most / all of your incoming requests?

Ocelot wasn't designed with that in mind initially thought it would be a good feature.

If I was you I would go with traefik! Seems to be quite decent. King and Tyk look good too.

**Comment by juancash** [comment]
In my case I have 3 api and I only want redirect the traffic via Ocelot, I thinked in the following configuration:

```
{
      "UpstreamPathTemplate": "/api/api1/{urlPath}",
      "UpstreamHttpMethod": "Get",
      "DownstreamPathTemplate": "/api/{urlPath}",
      "DownstreamScheme": "http",
      "DownstreamHost": "localhost",
      "DownstreamPort": 5001,
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 3,
        "DurationOfBreak": 10,
        "TimeoutValue": 10000
      }
    },
    {
      "UpstreamPathTemplate": "/api/api2/{urlPath}",
      "UpstreamHttpMethod": "Get",
      "DownstreamPathTemplate": "/api/{urlPath}",
      "DownstreamScheme": "http",
      "DownstreamHost": "localhost",
      "DownstreamPort": 5002,
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 3,
        "DurationOfBreak": 10,
        "TimeoutValue": 10000
      }
    },
    {
      "UpstreamPathTemplate": "/api/api3/{urlPath}",
      "UpstreamHttpMethod": "Get",
      "DownstreamPathTemplate": "/api/{urlPath}",
      "DownstreamScheme": "http",
      "DownstreamHost": "localhost",
      "DownstreamPort": 5003,
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 3,
        "DurationOfBreak": 10,
        "TimeoutValue": 10000
      }
    },
```
The requests to:

/api/api1 is redirected to port 5001
/api/api2 is redirected to port 5002
/api/api3 is redirected to port 5003

 I think this is possible. 
Could exists problems with some type of request?

**Comment by juancash** [comment]
Hi @TomPallister 

I created a fork of your project and created a branch to add this functionality. The changes are only a couple of lines. I don´t know if you want add this to your project. In affirmative case, say me what I must to do, because it´s my first time on github.

Thanks.

**Comment by TomPallister** [comment]
@juancash looks good, i left a comment on the PR if you could take a look. Thanks very much for your efforts!!

**Comment by juancash** [comment]
@Tom Acceptance test added to the PR #89.
Thanks to you for this great project.

**Comment by TomPallister** [comment]
@juancash thank you once again, I really liked the way you made this change! Very simple 👍
