### ISSUE TITLE
Going on holiday for 3 weeks does anybody want to maintain the project while I'm away? :)

### ISSUE THREAD

**Issue by TomPallister** [TomPallister/Ocelot#95]
Going on holiday for 3 weeks does anybody want to maintain the project while I'm away? :)

**Comment by juancash** [comment]
I´ll try to help as much as I can to people with doubts, but i cant cover all the project.

**Comment by TomPallister** [comment]
Thanks @juancash !

**Comment by TomPallister** [comment]
Im back! thanks for all the help.
